cmd/cloud-server/service/account/quota.go, cmd/cloud-server/service/vpc/vpc.go, docs/api-docs/web-server/docs/biz/list_huawei_account_region_quota.md, pkg/api/cloud-server/account/quota.go
1. 查询华为云配额接口添加云服务器当前已使用容量（used_instances）
2. 分配vpc添加是否绑定管控区域校验
=> optimize:1. 查询华为云配额接口添加云服务器当前已使用容量（used_instances） 2. 分配vpc添加是否绑定管控区域校验

cmd/cloud-server/logics/cvm/cvm.go, cmd/cloud-server/logics/cvm/delete.go, cmd/cloud-server/logics/disk/disk.go, cmd/cloud-server/logics/eip/eip.go, cmd/cloud-server/service/account/update.go, cmd/cloud-server/service/cvm/recycle.go, cmd/cloud-server/service/disk/recycle.go, cmd/data-service/service/cloud/account/update.go, pkg/adaptor/tcloud/disk.go, pkg/api/core/recycle-record/recycle_record.go, pkg/api/core/response.go, pkg/client/data-service/global/recycle_record.go, pkg/dal/dao/recycle-record/recycle_record.go, scripts/install/migrate.sh
fix: 修复磁盘回收问题：
1. 恢复cvm/回收失败时没有处理磁盘回收记录 
2. 回收站状态判断错误
3. 没有校验关联回收的情况
fix: 修复账号下回收时间修改不生效的问题
=> fix: 修复回收相关问题

pkg/adaptor/aws/eip.go, pkg/adaptor/gcp/cvm.go, pkg/tools/converter/converter.go
1. 修复Gcp主机关机Bug
2. 修复创建Aws Eip Bug
=> fix:1. 修复Gcp主机关机Bug 2. 修复创建Aws Eip Bug

cmd/cloud-server/service/application/approve.go, pkg/criteria/constant/error.go
=> fix: 修复单据一直处于交付中的bug

cmd/cloud-server/service/account/get.go, cmd/cloud-server/service/account/list.go, cmd/data-service/service/recycle-record/recycle_record.go, scripts/sql/9999.sql
=> fix: 用户未主动设置回收时长的情况下返回全局回收数据给前端

cmd/cloud-server/logics/async/wait.go, docs/api-docs/web-server/docs/resource/inquiry_price_cvm.md
=> fix: 异步任务返回第一个执行节点错误信息给到前端

cmd/cloud-server/service/disk/detach.go, pkg/adaptor/gcp/disk.go
optimize: 禁止卸载系统盘
fix: gcp硬盘卸载失败没有返回错误
=> optimize: 禁止卸载系统盘

cmd/cloud-server/service/account/get.go, cmd/data-service/service/cloud/account/create.go, cmd/hc-service/logics/res-sync/aws/disk.go, cmd/hc-service/logics/res-sync/azure/disk.go, cmd/hc-service/logics/res-sync/gcp/disk.go, cmd/hc-service/logics/res-sync/huawei/disk.go, pkg/adaptor/types/disk/aws.go, pkg/adaptor/types/disk/azure.go, pkg/adaptor/types/disk/gcp.go, pkg/adaptor/types/disk/huawei.go, pkg/criteria/constant/recycle.go, pkg/dal/table/cloud/account.go
=> feat: 同步磁盘的时候不主动清除系统盘标签

cmd/auth-server/types/types.go, cmd/data-service/service/auth/auth.go, pkg/dal/table/table.go, pkg/iam/sys/initial_action_groups.go, pkg/iam/sys/initial_actions.go, pkg/iam/sys/initial_instance_selections.go, pkg/iam/sys/initial_resource_creator_actions.go, pkg/iam/sys/initial_resources.go, pkg/iam/sys/types.go
=> feature: 添加初始化云选型权限

cmd/cloud-server/etc/cloud_server.yaml, docs/api-docs/web-server/docs/resource/cloud-selection/query_biz_latnecy.md, docs/api-docs/web-server/docs/resource/cloud-selection/query_ping_latnecy.md, pkg/cc/types.go
=> feat: 增加ping延迟和idc价格区间相关配置

cmd/auth-server/service/auth/adaptor.go, cmd/cloud-server/service/capability/capability.go, cmd/cloud-server/service/cloud-selection/bkbase.go, cmd/cloud-server/service/cloud-selection/service.go, cmd/cloud-server/service/service.go, docs/api-docs/web-server/docs/resource/cloud-selection/list_available_country.md, docs/api-docs/web-server/docs/resource/cloud-selection/query_idc_service_area.md, docs/api-docs/web-server/docs/resource/cloud-selection/query_ping_latnecy.md, pkg/api/cloud-server/cloud-selection/cloud_selection.go, pkg/api/core/cloud-selection/area.go, pkg/criteria/constant/time.go, pkg/iam/meta/resource.go, pkg/thirdparty/api-gateway/bkbase/bkbase.go, pkg/thirdparty/api-gateway/bkbase/types.go, pkg/tools/converter/converter.go, pkg/tools/times/time.go
1. ListAvailableCountry
2. QueryUserDistribution
3. QueryPingLatency
4. QueryBizLatency
5. QueryServiceArea
=> feat: BKBase 相关接口实现

pkg/criteria/validator/memo.go
=> fix: 添加账号时的memo长度校验

cmd/data-service/service/cloud/route-table/gcp_route.go, pkg/adaptor/azure/account.go, pkg/adaptor/azure/error.go, pkg/adaptor/gcp/account.go, pkg/dal/table/cloud/route-table/gcp_route.go
- fix: gcp账号获取不到project时导致的数组越界
- fix: 目标 IP 地址范围为单个ip时无法通过校验
- fix: 修正命名，指明是cloud vpc id
- fix: azure graph api 的错误信息展示
=> fix: 修复若干后端错误

front/src/views/scheme/scheme-recommendation/index.scss, front/src/views/scheme/scheme-recommendation/index.tsx
=> feat: 添加handle

.gitignore, front/src/views/business/load-balancer/clb-view/index.scss, front/src/views/business/load-balancer/clb-view/index.tsx, front/src/views/business/load-balancer/components/dynamic-tree/index.scss, front/src/views/business/load-balancer/components/dynamic-tree/index.tsx
=> feat: 新增树形控件-搜索及命中关键词高亮&全部展开以及全部收起

cmd/cloud-server/etc/cloud_server.yaml, cmd/cloud-server/service/cloud-selection/scheme.go, pkg/cc/types.go
增加独立参数`recommendDataSource`配置给推荐算法的数据源，默认为ping数据
=> feat: 可配置算法数据源

front/src/views/scheme/components/scheme-preview/components/scheme-preview-table-card/index.tsx
=> fix: 调整服务质量排名高度

front/src/router/module/resource.ts
=> feature: 开放账号管理页

front/src/assets/image/empty-table.svg, front/src/components/empty/index.scss, front/src/components/empty/index.tsx, front/src/hooks/useTable/index.scss, front/src/hooks/useTable/useTable.tsx, front/src/views/business/load-balancer/clb-view/index.scss, front/src/views/business/load-balancer/components/common-sideslider/index.scss, front/src/views/business/load-balancer/components/common-sideslider/index.tsx, front/src/views/business/load-balancer/group-view/index.scss, front/src/views/business/load-balancer/group-view/index.tsx, front/src/views/business/load-balancer/group-view/target-group-sideslider-content/index.scss, front/src/views/business/load-balancer/group-view/target-group-sideslider-content/index.tsx, front/src/views/business/load-balancer/index.scss, front/src/views/resource/resource-manage/hooks/use-columns.tsx
1、 目标组视角-全部-静态
2、 通用 sideslider 组件
3、 新建目标组 sideslider 表单 - 静态
4、 通用 Empty 组件
=> feat：新增一些静态页面&通用组件

cmd/cloud-server/service/account/get.go, cmd/hc-service/service/account/get.go, docs/api-docs/web-server/docs/resource/get_account.md, docs/api-docs/web-server/docs/resource/list_account.md, pkg/criteria/errf/check.go
解决合并冲突
* fix(tcloud/rescount): add sub account context canceled err filter
* feat(account/get): add sync detail
(cherry picked from commit 18242187b4fd590f51c08495491b914aed7ca913)
=> feat: get account 接口返回同步详情 (#535)

front/src/views/business/business-manage.vue, front/src/views/business/load-balancer/clb-view/all-clbs-manager/index.tsx, front/src/views/business/load-balancer/clb-view/specific-domain-manager/index.tsx, front/src/views/business/load-balancer/clb-view/specific-listener-manager/domain-list/index.tsx, front/src/views/business/load-balancer/components/dynamic-tree/index.tsx, front/src/views/business/load-balancer/group-view/all-groups-manager/index.tsx, front/src/views/business/load-balancer/index.scss, front/src/views/resource/recyclebin-manager/recyclebin-manager.vue, front/src/views/resource/resource-manage/children/manage/drive-manage.vue, front/src/views/resource/resource-manage/children/manage/host-manage.vue, front/src/views/resource/resource-manage/children/manage/ip-manage.vue, front/src/views/resource/resource-manage/children/manage/security-manage.vue, front/src/views/resource/resource-manage/children/manage/subnet-manage.vue, front/src/views/resource/resource-manage/children/manage/vpc-manage.vue, front/src/views/resource/resource-manage/hooks/use-columns.tsx, front/src/views/resource/resource-manage/resource-manage.vue
=> fix: 修复列表selection样式问题

pkg/adaptor/tcloud/account.go, pkg/adaptor/tcloud/bill.go, pkg/adaptor/tcloud/clb.go, pkg/adaptor/tcloud/client.go, pkg/adaptor/tcloud/cvm.go, pkg/adaptor/tcloud/disk.go, pkg/adaptor/tcloud/eip.go, pkg/adaptor/tcloud/image.go, pkg/adaptor/tcloud/instance_type.go, pkg/adaptor/tcloud/policy.go, pkg/adaptor/tcloud/region.go, pkg/adaptor/tcloud/route_table.go, pkg/adaptor/tcloud/security_group.go, pkg/adaptor/tcloud/security_group_rule.go, pkg/adaptor/tcloud/subnet.go, pkg/adaptor/tcloud/tcloud.go, pkg/adaptor/tcloud/vpc.go, pkg/adaptor/tcloud/zone.go
=> refactor(adaptor/tcloud): clientSet 接口化重构

front/src/common/constant.ts, front/src/components/common-sideslider/index.tsx, front/src/hooks/useTable/useTable.tsx, front/src/store/resource.ts, front/src/views/business/cert-manager/index.scss, front/src/views/business/cert-manager/index.tsx, front/src/views/business/load-balancer/clb-view/all-clbs-manager/index.tsx, front/src/views/business/load-balancer/components/dynamic-tree/index.tsx, front/src/views/resource/resource-manage/children/dialog/batch-distribution/index.tsx, front/src/views/resource/resource-manage/hooks/use-columns.tsx, front/src/views/resource/resource-manage/resource-manage.vue
=> feat: 证书托管接口联调&clb拓扑列表交互优化

pkg/adaptor/huawei/eip.go
=> fix(adaptor/huawei): 未判断ShowBandwidth错误

front/src/hooks/useTable/useTable.tsx, front/src/router/module/business.ts, front/src/router/module/resource.ts, front/src/store/useBusinessMap.ts, front/src/views/business/cert-manager/index.tsx, front/src/views/resource/resource-manage/account/createAccount/components/accountForm/index.tsx, front/src/views/resource/resource-manage/hooks/use-columns.tsx, front/src/views/resource/resource-manage/operationRecord/index.scss, front/src/views/resource/resource-manage/operationRecord/index.tsx, front/src/views/service/service-apply/cvm/index.tsx, front/src/views/service/service-apply/vpc/index.tsx
1. 遗留样式修复
2. 操作记录-安全组接口联调
3. 改造 useTable
=> feat: 操作记录-安全组

front/src/common/util.ts, front/src/hooks/useTable/useTable.tsx, front/src/views/business/cert-manager/index.tsx, front/src/views/resource/resource-manage/operationRecord/index.tsx
=> feat: 增强 useTable 的搜索功能

front/src/views/business/load-balancer/clb-view/all-clbs-manager/index.tsx, front/src/views/business/load-balancer/clb-view/specific-clb-manager/listener-list/index.tsx, front/src/views/business/load-balancer/clb-view/specific-domain-manager/index.tsx, front/src/views/business/load-balancer/clb-view/specific-listener-manager/domain-list/index.tsx, front/src/views/business/load-balancer/components/dynamic-tree/index.tsx, front/src/views/business/load-balancer/group-view/all-groups-manager/index.tsx, front/src/views/business/load-balancer/group-view/specific-target-group-manager/listener-list/index.tsx, front/src/views/service/service-apply/clb/index.tsx
=> refactor: useTable适配修复

front/src/common/constant.ts, front/src/views/resource/resource-manage/children/components/security/security-rule.vue
=> feature: 参数模板问题修复 --story=115986369 参数模板验收问题记录

cmd/cloud-server/service/service.go, cmd/cloud-server/service/sync/tcloud/sync_all_resource.go, cmd/hc-service/logics/res-sync/tcloud/security_group_rule.go, cmd/hc-service/service/security-group/tcloud_security_group_rule.go, pkg/adaptor/tcloud/security_group_rule.go, pkg/api/cloud-server/argument-template/argument_template.go
=> fix(argument template): 修复参数模版同步时，传入的cloud_id为空的问题

pkg/adaptor/tcloud/cert.go, pkg/adaptor/tcloud/client.go
=> fix(adaptor): 腾讯云证书部分未适配ClientSet接口

scripts/sql/9999_tcloud_clb.sql
=> feat: 负载均衡相关sql

front/.husky/pre-push, front/src/router/module/business.ts, front/src/views/business/business-detail.vue, front/src/views/resource/resource-manage/children/detail/template-detail/index.scss, front/src/views/resource/resource-manage/children/detail/template-detail/index.tsx, front/src/views/resource/resource-manage/children/dialog/template-dialog/index.tsx, front/src/views/resource/resource-manage/children/manage/security-manage.vue, front/src/views/resource/resource-manage/resource-detail.vue
=> feature: 新增参数模板详情页 & 修复验收已知问题

front/.husky/pre-push, front/src/router/module/business.ts, front/src/views/business/business-detail.vue, front/src/views/resource/resource-manage/children/detail/template-detail/index.scss, front/src/views/resource/resource-manage/children/detail/template-detail/index.tsx, front/src/views/resource/resource-manage/children/dialog/template-dialog/index.tsx, front/src/views/resource/resource-manage/children/manage/security-manage.vue, front/src/views/resource/resource-manage/resource-detail.vue
=>  fix：修复参数模板关联实例数不显示的问题 

pkg/dal/dao/cloud/clb/clb_flow_lock.go, pkg/dal/dao/cloud/clb/clb_flow_rel.go, pkg/dal/dao/cloud/clb/load_balancer.go, pkg/dal/dao/cloud/clb/load_balancer_listener.go, pkg/dal/dao/cloud/clb/load_balancer_target.go, pkg/dal/dao/cloud/clb/load_balancer_target_group.go, pkg/dal/dao/cloud/clb/target_listener_rule_rel.go, pkg/dal/dao/cloud/clb/tcloud_lb_url_rule.go, pkg/dal/dao/cloud/security-group-common-rel/security_group_common_rel.go, pkg/dal/dao/types/clb/clb_flow_lock.go, pkg/dal/dao/types/clb/clb_flow_rel.go, pkg/dal/dao/types/clb/load_balancer.go, pkg/dal/dao/types/clb/load_balancer_listener.go, pkg/dal/dao/types/clb/load_balancer_target.go, pkg/dal/dao/types/clb/load_balancer_target_group.go, pkg/dal/dao/types/clb/target_listener_rule_rel.go, pkg/dal/dao/types/clb/tcloud_lb_url_rule.go, pkg/dal/dao/types/security_group_common_rel.go, pkg/dal/table/cloud/clb/clb_flow_lock.go, pkg/dal/table/cloud/clb/clb_flow_rel.go, pkg/dal/table/cloud/clb/load_balancer.go, pkg/dal/table/cloud/clb/load_balancer_listener.go, pkg/dal/table/cloud/clb/load_balancer_target.go, pkg/dal/table/cloud/clb/load_balancer_target_group.go, pkg/dal/table/cloud/clb/target_listener_rule_rel.go, pkg/dal/table/cloud/clb/tcloud_lb_url_rule.go, pkg/dal/table/cloud/security_group_common_rel.go, pkg/dal/table/table.go, scripts/sql/9999_tcloud_clb.sql
=> feature(clb): 新增clb相关的数据表dao

front/src/views/resource/resource-manage/children/components/security/security-rule.vue, front/src/views/resource/resource-manage/children/dialog/security-rule/add-rule.tsx
=> fix: 修复安全组规则列表与编辑场景数据不回显的问题

cmd/cloud-server/service/security-group/associate_clb.go, cmd/cloud-server/service/security-group/init.go, cmd/cloud-server/service/security-group/query.go, cmd/data-service/service/audit/cloud/clb/base.go, cmd/data-service/service/audit/cloud/clb/operation_audit.go, cmd/data-service/service/audit/cloud/cloud_audit.go, cmd/data-service/service/audit/cloud/security-group/security_group.go, cmd/data-service/service/cloud/security-group-common-rel/create.go, cmd/data-service/service/cloud/security-group-common-rel/delete.go, cmd/data-service/service/cloud/security-group-common-rel/init.go, cmd/data-service/service/cloud/security-group-common-rel/query.go, cmd/hc-service/service/security-group/logics.go, cmd/hc-service/service/security-group/security_group.go, cmd/hc-service/service/security-group/tcloud_security_group.go, pkg/adaptor/tcloud/clb.go, pkg/adaptor/tcloud/interface.go, pkg/adaptor/types/clb/tcloud.go, pkg/api/core/cloud/security_group_common_rel.go, pkg/api/data-service/cloud/security_group_common_rel.go, pkg/api/hc-service/clb/tcloud.go, pkg/client/data-service/global/security_group_common_rel.go, pkg/client/hc-service/tcloud/security_group.go, pkg/tools/hooks/handler/operation.go
=> feat(clb:cloudserver、hcservice、dataservice、pkg): 提交业务下clb安全组绑定/解绑/列表的接口

docs/api-docs/web-server/docs/biz/clb/get_listener.md, docs/api-docs/web-server/docs/biz/clb/get_url_rule.md, docs/api-docs/web-server/docs/biz/clb/list_clb_with_listeners.md, docs/api-docs/web-server/docs/biz/clb/list_target_group_with_listeners.md, scripts/sql/9999_tcloud_clb.sql
=> docs(clb/listener): 新增业务下监听器列表及监听器详情、URL规则详情的接口文档

cmd/cloud-server/service/load-balancer/assign.go, cmd/cloud-server/service/load-balancer/create.go, cmd/cloud-server/service/load-balancer/lb_url_rule.go, cmd/cloud-server/service/load-balancer/listener.go, cmd/cloud-server/service/load-balancer/load_balancer.go, cmd/cloud-server/service/load-balancer/query.go, cmd/cloud-server/service/load-balancer/tcloud_describe_resources.go, cmd/cloud-server/service/load-balancer/update.go, cmd/cloud-server/service/security-group/associate_clb.go, cmd/cloud-server/service/security-group/init.go, cmd/data-service/service/cloud/load-balancer/query.go, cmd/hc-service/service/load-balancer/tcloud.go, cmd/hc-service/service/security-group/security_group.go, cmd/hc-service/service/security-group/tcloud_security_group.go, docs/api-docs/web-server/docs/biz/load-balancer/list_listeners_by_target_group_id.md, pkg/adaptor/tcloud/clb.go, pkg/adaptor/tcloud/interface.go, pkg/adaptor/types/load-balancer/tcloud.go, pkg/api/data-service/cloud/clb.go, pkg/api/hc-service/load-balancer/tcloud.go, pkg/client/hc-service/tcloud/clb.go, pkg/client/hc-service/tcloud/security_group.go
=> feat(cloud-server、pkg): 根据最新的接口文档，修改参数里面的lb_id等

cmd/hc-service/logics/res-sync/tcloud/security_group_rule.go
=> fix(hc-service): 修复sg环境安全组规则同步时，参数模版参数校验问题

cmd/cloud-server/service/load-balancer/load_balancer.go, cmd/cloud-server/service/load-balancer/target_group.go
=> feat(cloud-server): 修复目标组详情接口api错误问题

front/src/store/business.ts, front/src/views/business/load-balancer/group-view/all-groups-manager/index.tsx, front/src/views/business/load-balancer/group-view/all-groups-manager/rs-config-table/index.tsx, front/src/views/business/load-balancer/group-view/specific-target-group-manager/health-checkup/index.tsx, front/src/views/business/load-balancer/group-view/specific-target-group-manager/index.tsx, front/src/views/business/load-balancer/group-view/specific-target-group-manager/target-group-detail/index.tsx, front/src/views/resource/resource-manage/hooks/use-columns.tsx
--story=116567777 目标组-绑定监听器 (仅限空RS的监听器) -前端联调
=> feat: 获取目标组基本信息

cmd/cloud-server/service/load-balancer/listener.go, cmd/cloud-server/service/load-balancer/target_group.go
=> fix(cloud-server): 修复监听器列表查询count无效的问题

cmd/data-service/service/cloud/load-balancer/create.go, cmd/data-service/service/cloud/load-balancer/delete.go, cmd/data-service/service/cloud/load-balancer/load_balancer.go, cmd/data-service/service/cloud/load-balancer/query.go, cmd/data-service/service/cloud/load-balancer/update.go, cmd/hc-service/logics/res-sync/tcloud/load_balancer.go, pkg/api/cloud-server/load-balancer/load_balancer.go, pkg/api/core/cloud/load-balancer/load_balancer.go, pkg/api/core/cloud/load-balancer/target_group.go, pkg/api/data-service/cloud/load_balancer.go, pkg/dal/dao/cloud/load-balancer/clb_flow_lock.go, pkg/dal/dao/cloud/load-balancer/clb_flow_rel.go, pkg/dal/dao/cloud/load-balancer/load_balancer.go, pkg/dal/dao/cloud/load-balancer/load_balancer_listener.go, pkg/dal/dao/cloud/load-balancer/load_balancer_target.go, pkg/dal/dao/cloud/load-balancer/load_balancer_target_group.go, pkg/dal/dao/cloud/load-balancer/target_listener_rule_rel.go, pkg/dal/dao/cloud/load-balancer/tcloud_lb_url_rule.go, pkg/dal/dao/cloud/security-group-common-rel/security_group_common_rel.go, pkg/dal/dao/dao.go, pkg/dal/table/cloud/load-balancer/tcloud_lb_url_rule.go
--story=116332783 URL规则-批量删除URL
--story=116332759 URL规则-编辑URL规则基本信息
--story=116332454 URL规则-新增URL
=> feat(data): 腾讯云url规则创建、更新、删除

cmd/cloud-server/service/load-balancer/listener.go, cmd/cloud-server/service/load-balancer/load_balancer.go, cmd/cloud-server/service/load-balancer/tcloud_url_rule.go, cmd/data-service/service/cloud/load-balancer/create.go, cmd/data-service/service/cloud/load-balancer/query.go, cmd/data-service/service/cloud/load-balancer/update.go, cmd/hc-service/logics/res-sync/tcloud/load_balancer.go, docs/api-docs/web-server/docs/biz/load-balancer/list_tcloud_biz_listener_domains.md, pkg/adaptor/types/load-balancer/tcloud.go, pkg/api/core/cloud/load-balancer/load_balancer.go, pkg/api/core/cloud/load-balancer/tcloud.go, pkg/api/data-service/cloud/load_balancer.go, pkg/api/hc-service/load-balancer/tcloud.go, pkg/criteria/enumor/ip.go, pkg/dal/dao/tools/filter.go, pkg/dal/table/cloud/load-balancer/load_balancer.go, scripts/sql/9999_tcloud_clb.sql
--story=116444966 CLB 同步
--story=116321354 业务下-CLB列表
=> feat(tcloud): 负载均衡list接口增加lb_type、ip_version，ipv6 增加双栈、6转4 类型

pkg/adaptor/tcloud/listener.go, pkg/adaptor/types/load-balancer/tcloud.go, pkg/adaptor/types/poller_option.go, pkg/api/core/cloud/load-balancer/load_balancer.go
=> feat(pkg/adaptor): 提交腾讯云监听器、规则的adaptor接口

front/src/components/batch-operation-dialog/index.tsx, front/src/components/common-sideslider/index.tsx, front/src/views/business/load-balancer/clb-view/lb-tree/useLoadTreeData.ts, front/src/views/business/load-balancer/clb-view/specific-clb-manager/listener-list/index.tsx, front/src/views/business/load-balancer/clb-view/specific-domain-manager/index.tsx, front/src/views/business/load-balancer/clb-view/specific-listener-manager/domain-list/index.tsx, front/src/views/business/load-balancer/index.scss, front/src/views/resource/resource-manage/hooks/use-columns.tsx
--story=116448177
--story=116572002
--story=116326151
=> feat(lb-view): 右侧列表页面接口联调

pkg/adaptor/tcloud/clb.go, pkg/adaptor/tcloud/interface.go, pkg/adaptor/tcloud/listener.go, pkg/adaptor/types/load-balancer/tcloud.go
=> feat(pkg): 优化监听器、规则的adaptor接口异步查询Task状态的逻辑

cmd/cloud-server/service/load-balancer/create.go, cmd/cloud-server/service/load-balancer/listener.go, cmd/data-service/service/cloud/load-balancer/create.go, docs/api-docs/web-server/docs/biz/load-balancer/get_listener.md, pkg/adaptor/tcloud/listener.go, pkg/api/cloud-server/load-balancer/load_balancer.go, pkg/api/core/cloud/load-balancer/tcloud.go, pkg/api/data-service/cloud/target_group.go, scripts/sql/9999_tcloud_clb.sql
=> feat(pkg、cloud-server): 修复监听器详情接口缺少字段的问题等

cmd/cloud-server/service/load-balancer/create.go, cmd/cloud-server/service/load-balancer/load_balancer.go, cmd/cloud-server/service/load-balancer/update.go, cmd/data-service/service/cloud/load-balancer/create.go, cmd/data-service/service/cloud/load-balancer/delete.go, cmd/data-service/service/cloud/load-balancer/load_balancer.go, cmd/data-service/service/cloud/load-balancer/update.go, cmd/hc-service/service/load-balancer/tcloud.go, pkg/adaptor/tcloud/clb.go, pkg/adaptor/tcloud/listener.go, pkg/adaptor/types/load-balancer/tcloud.go, pkg/api/cloud-server/load-balancer/load_balancer.go, pkg/api/core/cloud/load-balancer/load_balancer.go, pkg/api/core/cloud/load-balancer/target_group.go, pkg/api/data-service/cloud/load_balancer.go, pkg/api/data-service/cloud/target_group.go, pkg/api/hc-service/load-balancer/tcloud.go, pkg/client/data-service/global/load_balancer.go, pkg/client/data-service/tcloud/load_balancer.go, pkg/client/hc-service/tcloud/clb.go, pkg/criteria/constant/clb.go, pkg/criteria/enumor/load_balancer.go, pkg/dal/dao/cloud/load-balancer/load_balancer_listener.go, pkg/dal/table/cloud/load-balancer/load_balancer_listener.go, pkg/dal/table/cloud/load-balancer/load_balancer_target_group.go
=> feat: 新增监听器创建、编辑的接口

cmd/cloud-server/service/load-balancer/listener.go, cmd/cloud-server/service/load-balancer/target_group.go
=> fix(cloud-server): 修复目标组、监听器详情接口查询问题

cmd/cloud-server/service/load-balancer/delete.go, cmd/cloud-server/service/load-balancer/load_balancer.go, cmd/data-service/service/audit/cloud/create_resource_delete_audit.go, cmd/data-service/service/audit/cloud/listener.go, cmd/data-service/service/cloud/load-balancer/delete.go, cmd/hc-service/service/load-balancer/tcloud.go, pkg/adaptor/tcloud/listener.go, pkg/api/hc-service/load-balancer/tcloud.go, pkg/client/data-service/global/load_balancer.go, pkg/client/hc-service/tcloud/clb.go, pkg/criteria/enumor/audit.go, pkg/rest/request.go
=> feat: 监听器删除接口

cmd/cloud-server/service/load-balancer/load_balancer.go, cmd/cloud-server/service/load-balancer/update.go, cmd/data-service/service/cloud/load-balancer/update.go, cmd/hc-service/service/load-balancer/tcloud.go, pkg/adaptor/tcloud/listener.go, pkg/adaptor/types/load-balancer/tcloud.go, pkg/api/data-service/cloud/target_group.go, pkg/api/hc-service/load-balancer/tcloud.go, pkg/client/hc-service/tcloud/clb.go
=> feat: 域名更新的接口

cmd/auth-server/service/auth/auth.go, cmd/cloud-server/logics/cvm/delete.go, cmd/cloud-server/service/application/handlers/base_cmdb.go, cmd/data-service/service/cloud/logics/cmdb/cmdb.go, cmd/web-server/service/cmdb/cmdb.go, cmd/web-server/service/cmdb/list_cloud_host.go, pkg/thirdparty/esb/cmdb/cmdb.go, pkg/thirdparty/esb/cmdb/get_biz_brief_cache_topo.go, pkg/thirdparty/esb/iam/iam.go, pkg/thirdparty/esb/login/login.go, pkg/thirdparty/esb/login/types.go, pkg/thirdparty/esb/types/types.go
* refactor(esb): 采用认证信息标准化方案调用esb API
* refactor(esb login): 采用认证信息标准化方案调用is_login API
https://github.com/TencentBlueKing/blueking-apigateway/issues/325
--story=116692136 esb标准化认证重构
=> refactor(esb): 采用认证信息标准化方案调用esb API

front/src/store/loadbalancer.ts, front/src/views/business/load-balancer/clb-view/lb-tree/index.tsx, front/src/views/business/load-balancer/clb-view/specific-clb-manager/security-group/expand-card/index.scss, front/src/views/business/load-balancer/clb-view/specific-clb-manager/security-group/expand-card/index.tsx, front/src/views/business/load-balancer/clb-view/specific-clb-manager/security-group/index.tsx
=> feat: 具体的负载均衡联调

cmd/hc-service/service/security-group/tcloud_security_group.go
=> fix(hc-service): 修复安全组绑定LB时DB删除失败的问题

cmd/data-service/service/cloud/load-balancer/create.go, cmd/data-service/service/cloud/load-balancer/load_balancer.go, cmd/data-service/service/cloud/load-balancer/query.go, cmd/hc-service/logics/res-sync/common/diff.go, cmd/hc-service/logics/res-sync/common/types.go, cmd/hc-service/logics/res-sync/tcloud/argument_template.go, cmd/hc-service/logics/res-sync/tcloud/load_balancer.go, cmd/hc-service/logics/res-sync/tcloud/load_balancer_listener.go, cmd/hc-service/service/load-balancer/tcloud.go, pkg/adaptor/tcloud/clb.go, pkg/adaptor/tcloud/interface.go, pkg/adaptor/tcloud/listener.go, pkg/api/core/cloud/load-balancer/tcloud.go, pkg/api/data-service/cloud/load_balancer.go, pkg/api/data-service/cloud/target_group.go, pkg/client/data-service/tcloud/load_balancer.go, pkg/criteria/constant/clb.go
--story=116578193 监听器-监听器及规则同步
--story=116676797 监听器同步
=> feat(hc): 腾讯云监听器层同步

front/.husky/pre-commit, front/src/components/common-sideslider/index.tsx, front/src/hooks/useTable/index.scss, front/src/hooks/useTable/useTable.tsx, front/src/views/business/load-balancer/clb-view/specific-clb-manager/security-group/index.scss, front/src/views/business/load-balancer/clb-view/specific-clb-manager/security-group/index.tsx
=> feat: 负载均衡绑定的安全组-绑定\解绑\搜索\查看详情

cmd/cloud-server/service/load-balancer/create.go, cmd/data-service/service/cloud/load-balancer/create.go, cmd/data-service/service/cloud/load-balancer/update.go, docs/api-docs/web-server/docs/biz/load-balancer/create_target_group.md, docs/api-docs/web-server/docs/biz/load-balancer/update_target_group.md, pkg/api/data-service/cloud/target_group.go
=> feat: 创建/更新目标组接口改为支持cloud_vpc_id

cmd/hc-service/service/load-balancer/tcloud.go, docs/api-docs/web-server/docs/biz/load-balancer/batch_create_tcloud_rules.md, docs/api-docs/web-server/docs/biz/load-balancer/create_listener.md, docs/api-docs/web-server/docs/biz/load-balancer/get_listener.md, docs/api-docs/web-server/docs/biz/load-balancer/update_listener.md, docs/api-docs/web-server/docs/biz/load-balancer/update_tcloud_rules.md
--story=116629969 HTTPS监听器证书、SNI字段修复
=> fix: 监听器证书更新

docs/api-docs/web-server/docs/biz/load-balancer/list_listeners_rules_by_target_group_id.md, docs/api-docs/web-server/docs/biz/load-balancer/update_domain.md
=> docs: 域名更新接口的文档，支持证书参数

cmd/data-service/service/cloud/account-biz-rel/query.go, cmd/data-service/service/cloud/load-balancer/create.go, cmd/data-service/service/cloud/load-balancer/update.go, cmd/hc-service/logics/res-sync/common/diff.go, cmd/hc-service/logics/res-sync/common/types.go, cmd/hc-service/logics/res-sync/tcloud/load_balancer.go, cmd/hc-service/logics/res-sync/tcloud/load_balancer_listener.go, cmd/hc-service/logics/res-sync/tcloud/load_balancer_rule.go, cmd/hc-service/service/load-balancer/tcloud.go, cmd/hc-service/service/load-balancer/tcloud_rule.go, pkg/adaptor/types/load-balancer/tcloud.go, pkg/api/core/cloud/load-balancer/load_balancer.go, pkg/api/core/cloud/load-balancer/tcloud.go, pkg/api/data-service/cloud/load_balancer.go, pkg/client/data-service/tcloud/load_balancer.go
=> feat(hc): 腾讯云监听器规则同步

front/src/store/business.ts, front/src/views/business/load-balancer/clb-view/specific-clb-manager/clb-detail/index.tsx, front/src/views/business/load-balancer/clb-view/specific-clb-manager/security-group/expand-card/index.scss, front/src/views/business/load-balancer/clb-view/specific-clb-manager/security-group/index.scss, front/src/views/business/load-balancer/clb-view/specific-clb-manager/security-group/index.tsx, front/src/views/business/load-balancer/clb-view/specific-listener-manager/domain-list/index.tsx, front/src/views/business/load-balancer/clb-view/specific-listener-manager/domain-list/useAddOrUpdateDomain.tsx
=> fix: 修复安全组验收问题

cmd/cloud-server/service/load-balancer/listener.go, cmd/data-service/service/cloud/load-balancer/query.go, cmd/hc-service/service/load-balancer/tcloud.go, pkg/api/cloud-server/load-balancer/load_balancer.go, pkg/api/core/cloud/load-balancer/load_balancer.go, pkg/api/data-service/cloud/load_balancer.go, pkg/client/data-service/tcloud/load_balancer.go
=> feat: 优化监听器列表、详情接口增加extension字段，修复四层监听器url数量问题

cmd/cloud-server/service/load-balancer/associate_target_group_listener.go, cmd/data-service/service/cloud/load-balancer/create.go, cmd/data-service/service/cloud/load-balancer/query.go, pkg/api/core/cloud/load-balancer/target_group.go, pkg/api/data-service/cloud/target_group.go, pkg/dal/table/cloud/load-balancer/target_group_listener_rule_rel.go, scripts/sql/9999_tcloud_clb.sql
`target_group_listener_rule_rel` 增加字段：
- `cloud_listener_rule_id`
- `cloud_target_group_id`
- `cloud_lb_id`
- `cloud_lbl_id`
--story=116676821
=> feat(data): 目标组监听器关系表增加cloud_id

cmd/cloud-server/service/audit/audit.go, docs/api-docs/web-server/docs/biz/load-balancer/batch_create_target_group_rs.md, docs/api-docs/web-server/docs/biz/load-balancer/get_record_async_task.md, docs/api-docs/web-server/docs/biz/load-balancer/update_target_group_rs_port.md, docs/api-docs/web-server/docs/biz/load-balancer/update_target_group_rs_weight.md, pkg/api/cloud-server/audit.go, pkg/api/data-service/audit/audit.go
=> feat: 异步任务详情接口

cmd/cloud-server/service/common/conv.go, cmd/cloud-server/service/load-balancer/create.go, cmd/cloud-server/service/load-balancer/delete.go, cmd/cloud-server/service/load-balancer/listener.go, cmd/cloud-server/service/load-balancer/load_balancer.go, cmd/data-service/service/cloud/load-balancer/create.go, cmd/data-service/service/cloud/load-balancer/query.go, cmd/hc-service/logics/res-sync/tcloud/load_balancer_target_group.go, cmd/hc-service/service/load-balancer/tcloud.go, cmd/hc-service/service/load-balancer/tcloud_target_group.go, cmd/task-server/logics/action/flow/query.go, cmd/task-server/logics/action/init.go, cmd/task-server/logics/action/load-balancer/target_group_rs.go, cmd/task-server/service/producer/producer.go, docs/api-docs/web-server/docs/biz/load-balancer/batch_create_target_group_rs.md, docs/api-docs/web-server/docs/biz/load-balancer/batch_delete_target_group_rs.md, pkg/api/cloud-server/load-balancer/load_balancer.go, pkg/api/core/cloud/load-balancer/target_group.go, pkg/api/data-service/cloud/target_group.go, pkg/api/hc-service/load-balancer/tcloud.go, pkg/async/consumer/scheduler.go, pkg/async/consumer/task.go, pkg/async/consumer/types.go, pkg/client/hc-service/tcloud/clb.go, pkg/criteria/constant/number.go, pkg/criteria/enumor/async_flow_name.go, pkg/criteria/enumor/async_task_name.go, pkg/criteria/enumor/load_balancer.go
=> feat: 目标组批量移除RS接口

front/src/common/constant.ts, front/src/store/business.ts, front/src/views/business/load-balancer/clb-view/specific-clb-manager/clb-detail/index.tsx, front/src/views/business/load-balancer/clb-view/specific-clb-manager/index.tsx, front/src/views/business/load-balancer/clb-view/specific-clb-manager/security-group/index.scss, front/src/views/business/load-balancer/clb-view/specific-clb-manager/security-group/index.tsx
--story=116574597 前端-业务下-CLB更新（基本信息比如删除保护、带宽上限）
=> feat: 更新CLB

cmd/cloud-server/service/load-balancer/create.go, cmd/cloud-server/service/load-balancer/delete.go, cmd/cloud-server/service/load-balancer/load_balancer.go, cmd/cloud-server/service/load-balancer/update.go, cmd/data-service/service/cloud/load-balancer/query.go, cmd/hc-service/service/load-balancer/tcloud.go, cmd/hc-service/service/load-balancer/tcloud_target_group.go, cmd/task-server/logics/action/init.go, cmd/task-server/logics/action/load-balancer/target_group_rs.go, docs/api-docs/web-server/docs/biz/load-balancer/update_target_group_rs_port.md, docs/api-docs/web-server/docs/biz/load-balancer/update_target_group_rs_weight.md, pkg/api/cloud-server/load-balancer/load_balancer.go, pkg/api/core/cloud/load-balancer/target_group.go, pkg/async/consumer/watch_dog.go, pkg/client/hc-service/tcloud/clb.go, pkg/criteria/constant/number.go, pkg/dal/table/cloud/load-balancer/load_balancer_target.go, scripts/sql/9999_tcloud_clb.sql
=> feat: 目标组批量修改RS端口接口

cmd/cloud-server/service/load-balancer/create.go, cmd/cloud-server/service/load-balancer/delete.go, cmd/cloud-server/service/load-balancer/load_balancer.go, cmd/cloud-server/service/load-balancer/update.go, cmd/hc-service/service/load-balancer/tcloud.go, cmd/hc-service/service/load-balancer/tcloud_target_group.go, cmd/task-server/logics/action/flow/query.go, cmd/task-server/logics/action/init.go, cmd/task-server/logics/action/load-balancer/target_group_rs.go, pkg/api/cloud-server/load-balancer/load_balancer.go, pkg/client/hc-service/tcloud/clb.go, pkg/criteria/constant/number.go
=> feat: 目标组批量修改RS权重接口

cmd/cloud-server/service/audit/audit.go, cmd/cloud-server/service/load-balancer/create.go, cmd/cloud-server/service/load-balancer/delete.go, cmd/cloud-server/service/load-balancer/tcloud_url_rule.go, cmd/cloud-server/service/load-balancer/update.go, cmd/data-service/service/cloud/load-balancer/create.go, cmd/data-service/service/cloud/load-balancer/delete.go, cmd/data-service/service/cloud/load-balancer/query.go, cmd/data-service/service/cloud/load-balancer/update.go, cmd/hc-service/service/load-balancer/tcloud_target_group.go, cmd/task-server/logics/action/init.go, cmd/task-server/logics/flow/build_task.go, cmd/task-server/logics/flow/load_balancer_operate_watch.go, docs/api-docs/web-server/docs/biz/load-balancer/get_record_async_flow.md, docs/api-docs/web-server/docs/biz/load-balancer/update_target_group_rs_weight.md, pkg/api/cloud-server/audit.go, pkg/api/data-service/cloud/load_balancer.go, pkg/criteria/enumor/async_flow_name.go, pkg/criteria/enumor/async_task_name.go, pkg/dal/dao/cloud/resource-flow/load_balancer_flow_lock.go, pkg/dal/dao/cloud/resource-flow/load_balancer_flow_rel.go, pkg/dal/dao/dao.go, pkg/dal/dao/types/load-balancer/load_balancer_flow_lock.go, pkg/dal/dao/types/load-balancer/load_balancer_flow_rel.go, pkg/dal/table/cloud/load-balancer/load_balancer_flow_lock.go, pkg/dal/table/cloud/load-balancer/load_balancer_flow_rel.go, pkg/dal/table/table.go, scripts/sql/9999_tcloud_clb.sql
=> feat: 异步任务详情接口、目标组批量操作接口优化，如果未绑定监听器则不再生成Task

front/src/common/util.ts, front/src/components/CommonLocalTable/index.scss, front/src/constants/clb.ts, front/src/constants/index.ts, front/src/hooks/useSelectOptionListWithScroll.ts, front/src/hooks/useTable/index.scss, front/src/style/override/bkinput.scss, front/src/style/override/index.scss, front/src/views/business/load-balancer/clb-view/lb-tree/index.tsx, front/src/views/business/load-balancer/clb-view/specific-clb-manager/listener-list/index.tsx, front/src/views/business/load-balancer/clb-view/specific-clb-manager/listener-list/useAddOrUpdateListener.ts, front/src/views/business/load-balancer/clb-view/specific-clb-manager/listener-list/useResolveListenerFormData.ts, front/src/views/business/load-balancer/clb-view/specific-listener-manager/domain-list/index.tsx, front/src/views/business/load-balancer/clb-view/specific-listener-manager/index.tsx, front/src/views/business/load-balancer/clb-view/specific-listener-manager/listener-detail/index.tsx, front/src/views/resource/resource-manage/hooks/use-columns.scss, front/src/views/resource/resource-manage/hooks/use-columns.tsx
=> fix: 优化CLB-监听器相关问题

cmd/cloud-server/service/load-balancer/create.go, cmd/cloud-server/service/load-balancer/listener.go, cmd/cloud-server/service/load-balancer/tcloud_url_rule.go, cmd/hc-service/service/load-balancer/tcloud.go, cmd/hc-service/service/load-balancer/tcloud_register_target.go, cmd/task-server/logics/action/load-balancer/bind_targets.go, cmd/task-server/logics/flow/load_balancer_operate_watch.go, pkg/api/cloud-server/load-balancer/load_balancer.go, pkg/api/hc-service/load-balancer/tcloud.go, pkg/client/hc-service/tcloud/clb.go
=> feat: 创建监听器时，支持绑定目标组对应的RS

cmd/cloud-server/service/load-balancer/load_balancer.go, cmd/cloud-server/service/load-balancer/query.go, cmd/hc-service/service/load-balancer/tcloud.go, cmd/hc-service/service/load-balancer/tcloud_target_group.go, docs/api-docs/web-server/docs/biz/load-balancer/list_target_health_by_target_group_id.md, pkg/adaptor/tcloud/client.go, pkg/adaptor/tcloud/interface.go, pkg/adaptor/tcloud/target.go, pkg/adaptor/types/load-balancer/tcloud.go, pkg/api/hc-service/load-balancer/tcloud.go, pkg/client/hc-service/tcloud/clb.go
=> feat: 查询指定的目标组绑定的负载均衡下的端口健康信息接口

cmd/cloud-server/service/audit/audit.go, cmd/cloud-server/service/load-balancer/create.go, cmd/cloud-server/service/load-balancer/delete.go, cmd/cloud-server/service/load-balancer/load_balancer.go, cmd/cloud-server/service/load-balancer/tcloud_url_rule.go, cmd/cloud-server/service/load-balancer/update.go, cmd/hc-service/service/load-balancer/tcloud_target_group.go, cmd/task-server/logics/flow/load_balancer_operate_watch.go, docs/api-docs/web-server/docs/biz/load-balancer/batch_create_target_group_rs.md, docs/api-docs/web-server/docs/biz/load-balancer/batch_delete_target_group_rs.md, docs/api-docs/web-server/docs/biz/load-balancer/get_record_async_flow.md, docs/api-docs/web-server/docs/biz/load-balancer/get_record_async_task.md, pkg/adaptor/tcloud/listener.go, pkg/api/cloud-server/audit.go, pkg/api/cloud-server/load-balancer/load_balancer.go, pkg/api/core/cloud/load-balancer/target_group.go, pkg/async/backend/mysql.go
=> feat: 批量添加/移除rs支持多目标组的操作

cmd/cloud-server/service/load-balancer/async.go, cmd/cloud-server/service/load-balancer/load_balancer.go, cmd/hc-service/service/load-balancer/tcloud.go, cmd/hc-service/service/load-balancer/tcloud_listener.go, docs/api-docs/web-server/docs/biz/load-balancer/async_flow_get_result_after_terminate.md, pkg/api/cloud-server/load-balancer/load_balancer.go, pkg/api/data-service/cloud/target_group.go, pkg/api/hc-service/load-balancer/tcloud.go, pkg/client/hc-service/tcloud/clb.go, pkg/criteria/enumor/load_balancer.go
--story=116333079 异步任务-异步任务终止后执行结果查询
=> feat(lb/async): 获取终止后异步任务结果

front/src/hooks/useTable/useTable.tsx, front/src/views/resource/resource-manage/operationRecord/RecordDetail/index.tsx, front/src/views/resource/resource-manage/operationRecord/RecordDetail/useFlowNode.tsx
=> feat: 异步任务详情联调

front/src/constants/clb.ts, front/src/hooks/useActiveTab.ts, front/src/router/module/business.ts, front/src/views/business/load-balancer/clb-view/index.tsx, front/src/views/business/load-balancer/clb-view/lb-tree/index.tsx, front/src/views/business/load-balancer/clb-view/specific-clb-manager/clb-detail/index.tsx, front/src/views/business/load-balancer/clb-view/specific-clb-manager/index.tsx, front/src/views/business/load-balancer/clb-view/specific-clb-manager/listener-list/index.tsx, front/src/views/business/load-balancer/clb-view/specific-domain-manager/index.tsx, front/src/views/business/load-balancer/clb-view/specific-listener-manager/domain-list/index.tsx, front/src/views/business/load-balancer/clb-view/specific-listener-manager/index.tsx, front/src/views/business/load-balancer/clb-view/specific-listener-manager/listener-detail/index.tsx, front/src/views/business/load-balancer/group-view/target-group-list/index.tsx, front/src/views/business/load-balancer/index.tsx, front/src/views/home/index.tsx
=> feat: 负载均衡-路由改造

cmd/cloud-server/service/load-balancer/create.go, cmd/hc-service/service/load-balancer/tcloud.go, pkg/adaptor/tcloud/listener.go, pkg/criteria/enumor/async_flow_name.go
=> feat: 优化创建监听器接口的证书逻辑

cmd/data-service/service/cloud/load-balancer/create.go, cmd/data-service/service/cloud/load-balancer/target_group.go, cmd/hc-service/logics/res-sync/tcloud/load_balancer_target_group.go
--story=117068771 监听器同步-未绑定RS的监听器，创建默认目标组
=> feat(tcloud/lb): 同步时为无RS的规则/监听器创建目标组

cmd/cloud-server/service/load-balancer/create.go, cmd/cloud-server/service/load-balancer/load_balancer.go, cmd/data-service/service/cloud/load-balancer/update.go, cmd/hc-service/logics/res-sync/tcloud/load_balancer.go, cmd/hc-service/service/load-balancer/tcloud.go, pkg/adaptor/types/load-balancer/tcloud.go, pkg/api/cloud-server/load-balancer/load_balancer.go, pkg/api/data-service/cloud/load_balancer.go, pkg/api/hc-service/load-balancer/tcloud.go
=> feat(tcloud/lb): 支持业务下直接创建负载均衡

cmd/cloud-server/service/load-balancer/inquiry_price.go, cmd/cloud-server/service/load-balancer/load_balancer.go, cmd/hc-service/service/load-balancer/tcloud.go, docs/api-docs/web-server/docs/resource/load-balancer/inquiry_load_balancer.md, pkg/adaptor/tcloud/clb.go, pkg/adaptor/tcloud/interface.go, pkg/adaptor/types/load-balancer/tcloud.go, pkg/api/cloud-server/load-balancer/load_balancer.go, pkg/api/hc-service/load-balancer/tcloud.go, pkg/client/hc-service/tcloud/clb.go
=> feat(tcloud/lb): 腾讯云负载均衡购买询价接口

front/package-lock.json, front/package.json
=> fix: 修复前端包版本问题

cmd/cloud-server/logics/cvm/assign.go, cmd/cloud-server/logics/disk/assign.go, cmd/cloud-server/logics/eip/assign.go, cmd/cloud-server/logics/network-interface/assign.go, cmd/cloud-server/service/load-balancer/target_group.go, cmd/data-service/service/cloud/load-balancer/query.go, cmd/hc-service/service/load-balancer/tcloud.go, docs/api-docs/web-server/docs/biz/load-balancer/update_target_group_health_check.md, pkg/client/hc-service/tcloud/clb.go, pkg/dal/dao/tools/filter.go, pkg/thirdparty/esb/types/types.go
--bug=123359361 【HCM】分配主机报错-EIP已存在
=>  fix: 支持关联资源已分配到业务下时分配CVM，支持目标组list指定字段

cmd/cloud-server/service/load-balancer/load_balancer.go, cmd/cloud-server/service/load-balancer/quota.go, cmd/hc-service/service/load-balancer/tcloud.go, docs/api-docs/web-server/docs/biz/load-balancer/list_tcloud_load_balancer_account_quota.md, pkg/adaptor/tcloud/clb.go, pkg/adaptor/tcloud/interface.go, pkg/adaptor/types/load-balancer/tcloud.go, pkg/api/hc-service/load-balancer/tcloud.go, pkg/client/hc-service/tcloud/clb.go
=> feat: 腾讯云负载均衡配额接口

front/src/components/common-sideslider/index.tsx, front/src/hooks/useTable/useTable.tsx, front/src/views/business/load-balancer/clb-view/components/AddOrUpdateDomainSideslider/index.tsx, front/src/views/business/load-balancer/clb-view/specific-clb-manager/security-group/index.tsx, front/src/views/business/load-balancer/group-view/all-groups-manager/useRenderTGList.tsx, front/src/views/resource/resource-manage/hooks/use-columns.scss, front/src/views/resource/resource-manage/hooks/use-columns.tsx
--story=117055692 【验收】【设计】异常端口数为0
--story=117055341 【验收】【前置】组目标，VPC需支持搜索
--story=117055140 【验收】【转发】编辑域名，提交增加loading状态（多次提交会报错）
--story=117055073 【验收】【前置】搜索改成模糊搜索
--story=117054852 【验收】【可用区未翻译
=> feat:优化异常端口数为0、目标组，VPC需支持搜索、编辑域名，提交增加加载状态、搜索修改成模糊搜索

cmd/hc-service/service/load-balancer/tcloud_rule.go
=> feat: 修复修改规则未传健康检查时的空指针问题

front/bk.config.js, front/package-lock.json, front/package.json, front/src/http/index.ts, front/static/login_success.html
--story=117011903 登录态失效使用window.open改造方案
=> feat：使用window open代替登录弹框

cmd/data-service/service/cloud/load-balancer/delete.go, cmd/data-service/service/cloud/security-group-common-rel/create.go, cmd/hc-service/logics/res-sync/common/types.go, cmd/hc-service/logics/res-sync/tcloud/load_balancer.go, cmd/hc-service/logics/res-sync/tcloud/load_balancer_security_group.go
--story=117206041 安全组-CLB的关联关系同步
=> feat(sync/lb): 支持腾讯云负载均衡与安全组关联关系的同步

front/src/views/business/load-balancer/clb-view/all-clbs-manager/index.tsx, front/src/views/business/load-balancer/clb-view/components/AddOrUpdateDomainSideslider/index.tsx, front/src/views/business/load-balancer/clb-view/specific-domain-manager/index.tsx, front/src/views/business/load-balancer/clb-view/specific-listener-manager/domain-list/index.tsx
--bug=123574843 【HCM-资源管理】域名新建成功后的数量计算不正确
--bug=123571253 【HCM-资源管理】负载均衡删除按钮不生效
=> fix:优化域名和URL新增删除时左侧列表数值不变问题、负载均衡删除按钮不生效

front/src/store/business.ts, front/src/views/business/load-balancer/clb-view/components/AddOrUpdateListenerSideslider/index.tsx, front/src/views/business/load-balancer/clb-view/components/AddOrUpdateListenerSideslider/useAddOrUpdateListener.ts
=> feat: 新增监听器前判断所属负载均衡是否锁定

cmd/cloud-server/logics/load-balancer/assign.go, cmd/cloud-server/service/load-balancer/assign.go, cmd/cloud-server/service/load-balancer/delete.go, cmd/cloud-server/service/sync/tcloud/load_balancer.go, cmd/data-service/service/cloud/load-balancer/load_balancer.go, cmd/data-service/service/cloud/load-balancer/update.go, cmd/hc-service/logics/res-sync/tcloud/load_balancer_security_group.go, pkg/adaptor/tcloud/clb.go, pkg/api/data-service/cloud/load_balancer.go, pkg/client/data-service/global/load_balancer.go, pkg/dal/dao/tools/filter.go
- fix: 修复删除负载均衡失败时空指针
- fix: 修复没有关联安全组时负载均衡报错
--story=117308447 负载均衡分配-关联资源分配
=> feat: 负载均衡分配时同时分配关联监听器、目标组，删除负载均衡时检查删除保护

front/src/constants/clb.ts, front/src/views/business/load-balancer/clb-view/all-clbs-manager/index.tsx, front/src/views/service/service-apply/clb/hooks/useRenderForm.tsx, front/src/views/service/service-apply/clb/index.scss
--bug=123786815 【必须】禁止删除的对象，删除按钮未禁用
--bug=123786869 【必须】vpc是region级别的，region下分az，az对应子网。所以表单次序需要调整下，可以参考腾讯云。
--bug=123786859 【必须】选项禁用需要tooltip说明原因
--bug=123786857 【必须】运营商类型决定负载均衡规格类型，因此选项次序调整下？
--bug=123786791 【必须】交互视线方面，可用区很容易被看漏了，不太顺畅。建议微调一下布局。
--bug=123786835 【必须】IPV4 IPV6大小写规范问题，应该为 IPv4 IPv6
=> fix:修复验收缺陷问题

cmd/auth-server/service/auth/gen_id.go, cmd/cloud-server/service/load-balancer/async.go, cmd/cloud-server/service/load-balancer/async_target_group_add_rs.go, cmd/cloud-server/service/load-balancer/create.go, pkg/criteria/errf/code.go, pkg/iam/sys/initial_action_groups.go, pkg/iam/sys/initial_actions.go, pkg/iam/sys/types.go, scripts/sql/9999_tcloud_clb.sql
=> feat: 新建4层监听器时增加rs、port的校验优化

cmd/hc-service/service/security-group/tcloud_security_group.go, pkg/api/hc-service/load-balancer/tcloud.go, pkg/criteria/constant/clb.go
=> feat: 负载均衡绑定安全组支持顺序调整功能

pkg/adaptor/poller/poller.go, pkg/adaptor/tcloud/cert.go
=> feat: 支持证书删除检查关联资源

cmd/data-service/service/cloud/load-balancer/delete.go
--story=117345558 负载均衡监听器/规则-目标组 关联关系删除
=> feat: 负载均衡监听器/规则-目标组的关联关系删除

cmd/cloud-server/service/load-balancer/async.go, pkg/async/consumer/consumer.go, pkg/async/consumer/scheduler.go, pkg/async/consumer/task.go, pkg/dal/table/async/types.go
=> feat: 支持已失败任务的取消、记录flow前一个状态

cmd/cloud-server/service/load-balancer/load_balancer.go, cmd/cloud-server/service/load-balancer/query.go, cmd/data-service/service/cloud/load-balancer/load_balancer.go, cmd/data-service/service/cloud/load-balancer/query.go, cmd/web-server/service/cloud/vpc/service.go, cmd/web-server/service/cloud/vpc/vpc.go, pkg/api/core/cloud/load-balancer/load_balancer.go, pkg/api/data-service/cloud/load_balancer.go, pkg/api/web-server/cloud/vpc.go, pkg/client/data-service/global/load_balancer.go
--story=115307381
--story=117441298 负载均衡-支持负载均衡列表返回删除保护
=> feat: 负载均衡列表支持返回删除保护、vpc带子网数量接口可用区非必填

cmd/cloud-server/service/load-balancer/async_target_group_add_rs.go, cmd/cloud-server/service/load-balancer/async_target_group_modify_port.go, cmd/cloud-server/service/load-balancer/async_target_group_modify_weight.go, cmd/cloud-server/service/load-balancer/async_target_group_remove_rs.go, cmd/cloud-server/service/load-balancer/create.go, cmd/cloud-server/service/load-balancer/query.go, cmd/cloud-server/service/load-balancer/tcloud_url_rule.go, docs/api-docs/web-server/docs/biz/load-balancer/get_load_balancer_lock_status.md, pkg/api/cloud-server/load-balancer/load_balancer.go, pkg/async/consumer/executor.go
=> feat: 负载均衡任务状态接口增加资源ID、任务ID字段，方便跳转到任务详情

front/src/common/constant.ts, front/src/common/util.ts, front/src/hooks/useTable/useTable.tsx, front/src/store/business.ts, front/src/views/business/cert-manager/index.tsx, front/src/views/business/load-balancer/clb-view/all-clbs-manager/index.tsx, front/src/views/business/load-balancer/clb-view/components/AddOrUpdateListenerSideslider/index.tsx, front/src/views/business/load-balancer/clb-view/components/AddOrUpdateListenerSideslider/useAddOrUpdateListener.ts, front/src/views/business/load-balancer/clb-view/specific-clb-manager/listener-list/index.tsx, front/src/views/business/load-balancer/clb-view/specific-domain-manager/index.tsx, front/src/views/business/load-balancer/group-view/all-groups-manager/useRenderTGList.tsx, front/src/views/business/load-balancer/group-view/components/AddOrUpdateTGSideslider/index.tsx, front/src/views/business/load-balancer/group-view/components/AddOrUpdateTGSideslider/useAddOrUpdateTGForm.tsx, front/src/views/resource/resource-manage/children/manage/load-balancer-manage.vue, front/src/views/resource/resource-manage/hooks/use-query-list-common.ts, front/src/views/resource/resource-manage/resource-manage.vue, front/src/views/service/service-apply/clb/hooks/useBottomBar.tsx, front/src/views/service/service-apply/clb/hooks/useRenderForm.tsx
--bug=123786983 【必须】同步状态一直不变
--bug=123786973 【必须】证书下拉选择 不知道 这个证书 支持哪些域名 @jojoojiang(蒋俊)
--bug=123786971 【必须】新建目标组报错，两个rsip的rsport不一致 @jojoojiang(蒋俊)
--bug=123787025 【必须】这里没有提示我创建子网，也没有拉出子网@jojoojiang(蒋俊)
--bug=123787021 【必须】这里子网要做了分配后才能被拉出来 需要一个引导@zhaosongwu(吴兆松)
--bug=123787001 【必须】点击配置安全组规则时，前端异常@jojoojiang(蒋俊)
--bug=123786985 【必须】添加监听器，会话保持可以有腾讯云的提示和文档链接 @jojoojiang(蒋俊)
--bug=123786931 【必须】新购买成功的负载均衡表格底没有标绿 @jojoojiang(蒋俊)
--bug=123786927 【必须】配置费用应该为hover唤出，当前需要点击
=> fix:解决分配的缺陷问题

front/src/views/business/load-balancer/clb-view/specific-clb-manager/security-group/index.tsx
=> feat: 修复负载均衡绑定安全组自测问题

cmd/cloud-server/service/account/get.go, docs/api-docs/web-server/docs/resource/get_account_by_secret.md, pkg/api/cloud-server/account/get.go
=> feat: 根据秘钥获取账号接口支持不检查主账号重复

front/src/components/common-sideslider/index.tsx, front/src/views/business/load-balancer/clb-view/specific-clb-manager/security-group/index.tsx, front/src/views/resource/resource-manage/children/dialog/security-rule/security-rule-validators.ts
=> feat: 调整自测问题

front/src/views/resource/accountmanage/account-detail.tsx, front/src/views/resource/resource-manage/account/createAccount/components/accountForm/useSecretExtension.tsx
=> feat:账号编辑密钥提交失败

cmd/cloud-server/service/load-balancer/tcloud_url_rule.go, cmd/data-service/service/cloud/cert/create.go, cmd/data-service/service/cloud/cert/query.go, cmd/data-service/service/cloud/cert/update.go, cmd/hc-service/logics/res-sync/tcloud/cert.go, cmd/hc-service/service/load-balancer/tcloud.go, cmd/hc-service/service/load-balancer/tcloud_rule.go, pkg/api/cloud-server/load-balancer/load_balancer.go, pkg/api/core/cloud/cert/cert.go, pkg/api/data-service/cloud/cert.go, pkg/dal/table/cloud/cert/cert.go, scripts/sql/9999_tcloud_clb.sql
=> feat: 监听器创建接口规则证书参数优化

cmd/cloud-server/service/cloud-selection/bkbase.go, cmd/cloud-server/service/cloud-selection/scheme.go, cmd/hc-service/logics/sync/syncer.go, pkg/criteria/constant/time.go, pkg/thirdparty/api-gateway/bkbase/types.go, pkg/tools/times/time.go
=> fix: cloud selection code review issues

front/src/http/index.ts
=> feat: 登录态失效使用window.open改造方案

cmd/cloud-server/service/load-balancer/listener.go, cmd/hc-service/service/load-balancer/tcloud_rule.go
=> feat: 监听器接口优化证书及域名数量逻辑

front/src/router/module/resource.ts, front/src/views/business/load-balancer/clb-view/all-clbs-manager/useBatchDeleteLB.ts
--bug=123787001 【必须】点击配置安全组规则时，前端异常
--bug=123787023 【必须】这里应该默认展示 可删除？
=> fix:这里应该默认展示 可删除？、点击配置安全组规则时，前端异常

front/src/views/business/load-balancer/clb-view/components/AddOrUpdateListenerSideslider/index.tsx, front/src/views/business/load-balancer/clb-view/components/CertSelector/index.tsx, front/src/views/business/load-balancer/group-view/components/AddOrUpdateTGSideslider/useAddOrUpdateTGForm.tsx, front/src/views/service/service-apply/components/common/region-vpc-selector/index.tsx
=> fix: 修复目标组编辑功能异常

front/src/views/business/load-balancer/group-view/components/AddOrUpdateTGSideslider/useAddOrUpdateTGForm.tsx
=> fix: 修复目标组编辑功能异常-补充

front/src/components/common-dialog/index.scss, front/src/hooks/useSingleList.ts, front/src/typings/common.ts, front/src/views/business/load-balancer/group-view/all-groups-manager/index.tsx, front/src/views/business/load-balancer/group-view/components/AddRsDialog/index.tsx, front/src/views/business/load-balancer/group-view/components/AddRsDialog/useAddRsTable.tsx, front/src/views/business/load-balancer/group-view/components/RsConfigTable/index.tsx, front/src/views/service/service-apply/components/common/region-vpc-selector/index.tsx
=> fix(add-rs): 修复编辑操作获取不到rs列表的问题

front/src/views/business/load-balancer/clb-view/specific-clb-manager/security-group/index.tsx
=> feat: 调整安全组勾选状态

cmd/cloud-server/service/load-balancer/listener.go, cmd/cloud-server/service/load-balancer/load_balancer.go, cmd/cloud-server/service/load-balancer/target_group.go, cmd/data-service/service/cloud/load-balancer/create.go, cmd/hc-service/logics/res-sync/tcloud/load_balancer_listener.go, docs/api-docs/web-server/docs/biz/load-balancer/create_listener.md, docs/api-docs/web-server/docs/biz/load-balancer/list_listeners_by_load_balancer_id.md, docs/api-docs/web-server/docs/biz/load-balancer/stat_target_group_rs_weight.md, pkg/adaptor/tcloud/listener.go, pkg/api/cloud-server/load-balancer/load_balancer.go, pkg/api/core/cloud/load-balancer/tcloud.go, pkg/api/data-service/cloud/target_group.go, pkg/api/hc-service/load-balancer/tcloud.go, pkg/client/data-service/tcloud/load_balancer.go
=> feat: 监听器支持端口段，重构监听器列表接口

cmd/cloud-server/service/load-balancer/async_target_group_add_rs.go, cmd/cloud-server/service/load-balancer/tcloud_url_rule.go, cmd/data-service/service/cloud/load-balancer/create.go, cmd/data-service/service/cloud/load-balancer/query.go, cmd/hc-service/logics/res-sync/tcloud/load_balancer.go, cmd/hc-service/logics/res-sync/tcloud/load_balancer_target_group.go, cmd/hc-service/service/load-balancer/tcloud.go, cmd/hc-service/service/load-balancer/tcloud_register_target.go, cmd/hc-service/service/load-balancer/tcloud_target_group.go, docs/api-docs/web-server/docs/biz/load-balancer/list_tcloud_load_balancer_account_quota.md, pkg/adaptor/types/load-balancer/tcloud.go, pkg/api/core/cloud/load-balancer/target_group.go, pkg/api/core/cloud/load-balancer/tcloud.go, pkg/api/data-service/cloud/target_group.go, pkg/api/hc-service/load-balancer/tcloud.go, pkg/criteria/errf/error.go, pkg/dal/table/cloud/load-balancer/load_balancer_target.go, scripts/sql/9999_cross_region_rs.sql
- 修改load_balancer_targets表：
1. 增加ip字段
2. 唯一键(TargetGroupID,CloudInstID,Port) 修改为(TargetGroupID,IP,Port,CloudInstID)
--story=117707790
=> feat: 以IP和端口为RS唯一键，支持ENI类型RS同步

front/src/store/loadbalancer.ts, front/src/views/business/load-balancer/clb-view/lb-tree/index.tsx, front/src/views/business/load-balancer/clb-view/specific-listener-manager/listener-detail/index.tsx, front/src/views/business/load-balancer/group-view/components/AddOrUpdateTGSideslider/index.tsx, front/src/views/business/load-balancer/group-view/components/RsConfigTable/index.tsx, front/src/views/business/load-balancer/group-view/specific-target-group-manager/index.tsx, front/src/views/business/load-balancer/group-view/specific-target-group-manager/listener-list/index.tsx, front/src/views/resource/resource-manage/hooks/use-columns.tsx
=> feat:  公有云-CLB-端口段信息展示 --story=117698119

cmd/Makefile, cmd/account-server/Makefile, cmd/account-server/account_server.go, cmd/account-server/app/app.go, cmd/account-server/etc/account_server.yaml, cmd/account-server/logics/audit/audit.go, cmd/account-server/options/options.go, cmd/account-server/service/capability/capability.go, cmd/account-server/service/main-account/get.go, cmd/account-server/service/main-account/service.go, cmd/account-server/service/service.go, cmd/api-server/service/proxy.go, cmd/web-server/service/proxy.go, pkg/api/account-server/account.go, pkg/cc/cc.go, pkg/cc/load.go, pkg/cc/service.go, pkg/client/account-server/client.go, pkg/client/api.go, scripts/install/start_all.sh, scripts/install/stop_all.sh
=> feat: 账号账单微服务后台框架

cmd/cloud-server/service/load-balancer/query.go, cmd/hc-service/service/load-balancer/tcloud_target_group.go, pkg/adaptor/tcloud/listener.go
=> feat: 修改添加rs、健康检查接口使用负载均衡所在region

front/.husky/pre-commit, front/package.json
=> feat: 动态编译配置

cmd/cloud-server/logics/load-balancer/assign.go
=> feat: 支持分批分配负载均衡关联资源

front/bk.config.js, front/src/hooks/useTable/index.scss, front/src/hooks/useTable/useTable.tsx, front/src/plugin-handler/useTable.ts, front/src/style/override/bktable.scss, front/tsconfig.json
=> feat: 插件化改造

cmd/hc-service/logics/res-sync/tcloud/load_balancer.go, cmd/hc-service/logics/res-sync/tcloud/load_balancer_rule.go, cmd/hc-service/logics/res-sync/tcloud/load_balancer_target_group.go
=> feat: 负载均衡相关资源同步增删改操作支持分批

front/src/hooks/useTable/useTable.tsx
=> feat: useTable支持本地分页

cmd/hc-service/logics/cloud-adaptor/cloud_client.go, cmd/hc-service/logics/cloud-adaptor/secret.go
=> feat: support root account cloud client

cmd/api-server/app/app.go, cmd/web-server/service/service.go
=> fix: web server request account server 405

cmd/cloud-server/service/application/handlers/load_balancer/tcloud/constants.go, cmd/cloud-server/service/application/handlers/load_balancer/tcloud/create_itsm_ticket.go, cmd/hc-service/logics/res-sync/tcloud/load_balancer.go, cmd/hc-service/logics/res-sync/tcloud/load_balancer_listener.go, cmd/hc-service/logics/res-sync/tcloud/load_balancer_target_group.go, pkg/adaptor/types/load-balancer/tcloud.go, pkg/api/hc-service/load-balancer/tcloud.go
复用云上负载均衡实例以降低云api接口压力
修复负载均衡单据网络计费类型字段
--story=117770324
=> feat: 修正负载均衡同步错误、监听器同步复用云上负载均衡实例

cmd/account-server/service/account-set/root-account/add.go, cmd/account-server/service/account-set/root-account/get.go, cmd/account-server/service/account-set/root-account/list.go, cmd/account-server/service/account-set/root-account/update.go, cmd/data-service/service/account-set/root-account/service.go, pkg/api/account-server/account-set/root_account.go, pkg/api/data-service/account-set/main_account.go, pkg/api/data-service/account-set/root_account.go, pkg/client/data-service/aws/root_account.go, pkg/client/data-service/azure/root_account.go, pkg/client/data-service/gcp/root_account.go, pkg/client/data-service/huawei/root_account.go, pkg/client/data-service/kaopu/root_account.go, pkg/client/data-service/zenlayer/root_account.go
=> fix: get root account basic info failed update params check

cmd/cloud-server/service/application/create.go, cmd/cloud-server/service/application/handlers/main-account/create-main-account/create_itsm_ticket.go, pkg/api/cloud-server/application/main_account.go
=> feat: disable DeptID and params validate optimize

cmd/auth-server/service/iam/list_instance.go, cmd/auth-server/types/types.go, cmd/data-service/service/auth/auth.go, pkg/api/data-service/account-set/main_account.go, pkg/api/data-service/account-set/root_account.go, pkg/dal/dao/auth/auth.go, pkg/dal/dao/types/auth.go
=> feat: auth resource main account list suppot and details bug fix

cmd/cloud-server/service/application/complete.go, cmd/cloud-server/service/application/create.go, cmd/cloud-server/service/application/handlers/main-account/create-main-account/complete.go, cmd/cloud-server/service/application/handlers/main-account/update-main-account/create_itsm_ticket.go, cmd/cloud-server/service/application/handlers/main-account/update-main-account/deliver.go, cmd/cloud-server/service/application/init.go, pkg/iam/auth/auth.go
=> feat: complete create main account and auth optimize

front/package-lock.json, front/package.json, front/src/api/bill/index.ts, front/src/components/CommonLocalTable/index.tsx, front/src/components/confirm/index.module.scss, front/src/components/confirm/index.tsx, front/src/constants/bill.ts, front/src/constants/index.ts, front/src/hooks/useSingleList.ts, front/src/hooks/useTable/index.module.scss, front/src/hooks/useTable/useTable.tsx, front/src/typings/bill.ts, front/src/views/bill/bill/adjust/batch-operation/index.tsx, front/src/views/bill/bill/adjust/index.tsx, front/src/views/bill/bill/components/search/index.tsx, front/src/views/bill/bill/components/search/operation-product-selector.tsx, front/src/views/bill/bill/components/search/sub-account-selector.tsx, front/src/views/bill/bill/detail/RenderTable/index.tsx, front/src/views/bill/bill/detail/index.tsx, front/src/views/bill/bill/index.tsx, front/src/views/bill/bill/summary/primary/index.tsx, front/src/views/bill/bill/summary/product/index.tsx, front/src/views/bill/bill/summary/sub/index.tsx, front/src/views/resource/resource-manage/hooks/use-columns.tsx
- 汇总列表
- 明细列表
- 调账列表、确认、删除
--story=118132310
--story=117919077
=> feat: 云账单联调

cmd/account-server/service/account-set/root-account/add.go, cmd/cloud-server/service/application/handlers/main-account/create-main-account/complete.go, cmd/data-service/service/account-set/main-account/create.go, cmd/hc-service/service/main-account/aws.go, cmd/hc-service/service/main-account/gcp.go, cmd/hc-service/service/main-account/service.go, cmd/hc-service/service/service.go, pkg/adaptor/gcp/client.go, pkg/adaptor/gcp/gcp.go, pkg/adaptor/gcp/main_account.go, pkg/adaptor/types/poller_option.go, pkg/api/core/account-set/root_account.go, pkg/api/data-service/account-set/root_account.go, pkg/api/hc-service/main-account/aws.go, pkg/api/hc-service/main-account/create.go, pkg/api/hc-service/main-account/gcp.go, pkg/client/hc-service/gcp/client.go, pkg/client/hc-service/gcp/main_account.go
=> feat: gcp main account auto create

front/src/views/home/business-selector/index.tsx, front/src/views/home/hooks/useChangeHeaderTab.ts, front/src/views/home/index.tsx
=> feat:  优化-资源管理下的业务选择器

cmd/cloud-server/service/application/complete.go, cmd/cloud-server/service/application/handlers/main-account/create-main-account/complete.go
=> feat: optimize account complete logic

front/src/api/bill/index.ts, front/src/common/constant.ts, front/src/constants/bill.ts, front/src/hooks/useTable/useTable.tsx, front/src/typings/bill.ts, front/src/views/bill/bill/components/amount/index.module.scss, front/src/views/bill/bill/components/amount/index.tsx, front/src/views/bill/bill/components/search/index.tsx, front/src/views/bill/bill/components/search/primary-account-selector.tsx, front/src/views/bill/bill/detail/RenderTable/index.tsx, front/src/views/bill/bill/summary/primary/index.tsx, front/src/views/bill/bill/summary/primary/recalculate/index.tsx, front/src/views/bill/bill/summary/product/index.tsx, front/src/views/bill/bill/summary/sub/index.tsx, front/src/views/resource/resource-manage/hooks/use-columns.tsx
--story=118158672
--story=117919077
=> feat: 云账单联调-问题修复&总金额、重新核算

cmd/auth-server/types/types.go, cmd/cloud-server/service/application/handlers/main-account/create-main-account/check.go, cmd/cloud-server/service/application/handlers/main-account/create-main-account/complete.go, cmd/data-service/service/account-set/main-account/create.go, cmd/data-service/service/account-set/main-account/get.go, cmd/data-service/service/account-set/main-account/list.go, cmd/data-service/service/auth/auth.go, pkg/api/core/account-set/main_account.go, pkg/api/data-service/account-set/main_account.go, pkg/dal/dao/account-set/main_account.go, pkg/dal/table/account-set/main_account.go, scripts/sql/9999_20240603_1700_account.sql
=> feat: add name field for main account table

cmd/account-server/service/account-set/root-account/add.go, cmd/auth-server/types/types.go, cmd/cloud-server/service/application/handlers/main-account/create-main-account/check.go, cmd/cloud-server/service/application/handlers/main-account/create-main-account/complete.go, cmd/cloud-server/service/application/handlers/main-account/update-main-account/deliver.go, cmd/data-service/service/account-set/main-account/create.go, cmd/data-service/service/account-set/main-account/get.go, cmd/data-service/service/account-set/main-account/list.go, cmd/data-service/service/auth/auth.go, cmd/hc-service/service/main-account/aws.go, pkg/adaptor/aws/main_account.go, pkg/adaptor/gcp/main_account.go, pkg/api/core/account-set/main_account.go, pkg/api/core/account-set/root_account.go, pkg/api/data-service/account-set/main_account.go, pkg/client/hc-service/aws/client.go, pkg/client/hc-service/aws/main_account.go, pkg/dal/dao/account-set/main_account.go, pkg/dal/table/account-set/main_account.go, scripts/sql/9999_20240603_1700_account.sql
=> feat: support aws auto create and bug fix

front/src/common/util.ts, front/src/components/business-selector/index.vue, front/src/components/vendor-radio-group/index.tsx, front/src/constants/bill.ts, front/src/views/bill/bill/adjust/create/index.tsx, front/src/views/bill/bill/components/search/index.tsx, front/src/views/bill/bill/components/search/primary-account-selector.tsx, front/src/views/bill/bill/components/search/sub-account-selector.tsx, front/src/views/bill/bill/detail/RenderTable/index.tsx, front/src/views/bill/bill/detail/index.tsx, front/src/views/bill/bill/header/index.tsx, front/src/views/home/index.tsx, front/src/views/resource/resource-manage/common/header/detail-header.tsx, front/src/views/resource/resource-manage/hooks/use-columns.tsx
- 业务保存
- 搜索条件联动过滤
- 账单明细列表查询增加限制 
--story=118158672
--story=117919077
=> feat: 云账单管理-问题修复

front/.husky/pre-commit, front/src/store/useBillStore.ts, front/src/views/bill/account/account-detail/first-level-account-detail/index.tsx, front/src/views/bill/account/account-detail/second-level-account-detail/index.tsx, front/src/views/bill/account/create-account/create-second-account/index.tsx, front/src/views/service/apply-detail/account-apply-detail/constants.ts, front/src/views/service/apply-detail/account-apply-detail/index.tsx
=> feat: 账号单据流程优化

cmd/account-server/service/bill/billadjustment/bill_adjustment.go, cmd/data-service/service/bill/billadjustmentitem/query.go, cmd/data-service/service/bill/billadjustmentitem/update.go, pkg/api/account-server/bill/billadjustmentitem.go, pkg/api/data-service/bill/billadjustmentitem.go, pkg/dal/dao/bill/billadjustmentitem.go, pkg/dal/table/bill/billadjustmentitem.go
=> feat: 调账相关创建/编辑字段调整

front/src/components/RenderDetailEdit/index.tsx, front/src/store/common.ts, front/src/views/bill/account/account-detail/second-level-account-detail/index.tsx, front/src/views/bill/account/account-manage/panel/index.tsx
=> feat: 账号管理-页面预鉴权-二级账号编辑

front/src/views/resource/resource-manage/hooks/use-columns.tsx
=> fix:  账号管理-账单页面-账单汇总-二级账号展示云上信息

front/src/components/business-selector/index.vue, front/src/hooks/useWhereAmI.ts, front/src/store/common.ts, front/src/views/home/index.tsx, front/src/views/resource/resource-manage/account/accountList/index.tsx, front/src/views/scheme/scheme-list/index.tsx, front/src/views/scheme/scheme-recommendation/index.tsx
=> feat: 资源管理&资源接入&云资源选型预鉴权优化

cmd/account-server/service/bill/billsummarymain/list.go, pkg/api/account-server/bill/billsummarymain.go
feat: 账号管理-账单列表-显示二级账号的云上ID --story=118289639
=> feat: 账号管理-账单列表-显示二级账号的云上ID --story=118289639

front/src/components/business-selector/index.vue, front/src/views/bill/bill/adjust/create/RenderTable/index.tsx, front/src/views/bill/bill/components/search/index.tsx, front/src/views/bill/bill/components/search/primary-account-selector.tsx, front/src/views/bill/bill/components/search/sub-account-selector.tsx, front/src/views/bill/bill/components/search/vendor-selector.tsx
=> feat: 账号管理-不同查询条件之间的级联

front/src/hooks/useWhereAmI.ts, front/src/views/business/load-balancer/clb-view/all-clbs-manager/index.tsx, front/src/views/business/load-balancer/clb-view/lb-tree/index.tsx, front/src/views/business/load-balancer/group-view/components/AddOrUpdateTGSideslider/index.tsx, front/src/views/business/load-balancer/group-view/specific-target-group-manager/index.tsx, front/src/views/business/load-balancer/group-view/specific-target-group-manager/listener-list/index.tsx, front/src/views/resource/resource-manage/common/table/HostOperations.tsx
- 刷新后useSingleList hooks函数业务id丢失
- lbtree定位时TCP, UDP请求了下级资源列表
- 主机批量操作弹框按钮无效
--story=117900461
=> feat: 修复前端自测问题

cmd/account-server/service/bill/billadjustment/service.go, cmd/account-server/service/bill/billadjustment/sum.go, pkg/api/account-server/bill/billitem.go
feat: 调账-共计增加-共计减少统计接口 --story=118328162
=> feat: 调账-共计增加-共计减少统计接口 --story=118328162

front/src/components/RenderDetailEdit/index.tsx
=> feat: 页面预鉴权补充

front/src/api/bill/index.ts, front/src/views/bill/bill/header/index.scss, front/src/views/bill/bill/header/index.tsx
=> feat: 账号管理-账单汇率显示

front/src/components/CommonLocalTable/index.tsx, front/src/hooks/useTable/useTable.tsx, front/src/router/module/bill.ts, front/src/router/module/business.ts, front/src/router/module/service.ts, front/src/router/module/workbench.ts, front/src/views/home/breadcrumb.tsx, front/src/views/home/index.tsx
=> feat: menu方案调整

front/src/views/bill/bill/components/search/index.tsx, front/src/views/bill/bill/components/search/sub-account-selector.tsx
=> feat: 二级账号保存支持可配置

front/src/components/common-sideslider/index.tsx, front/src/components/vendor-radio-group/index.tsx, front/src/views/bill/account/create-account/create-second-account/index.tsx, front/src/views/bill/bill/adjust/create/AdjustTable/index.tsx, front/src/views/bill/bill/adjust/create/RenderTableRow/index.tsx, front/src/views/bill/bill/adjust/create/index.tsx, front/src/views/bill/bill/components/search/primary-account-selector.tsx, front/src/views/resource/resource-manage/hooks/use-columns.tsx
=> feat: 账号账单问题优化

front/src/components/vendor-radio-group/index.tsx, front/src/views/bill/bill/adjust/create/RenderTableRow/index.tsx, front/src/views/bill/bill/components/search/vendor-selector.tsx
=> feat: 账单问题优化-限定调账金额最小值为0&去除腾讯云选项

cmd/account-server/logics/bill/manager.go, cmd/account-server/logics/bill/rootaccount_controller.go, cmd/task-server/logics/action/bill/mainsummary/mainsummary.go, cmd/task-server/logics/action/bill/rootsummary/rootsummary.go, front/src/components/vendor-radio-group/index.tsx, front/src/views/bill/bill/adjust/create/RenderTableRow/index.tsx, front/src/views/bill/bill/components/search/vendor-selector.tsx, scripts/sql/9999_20240531_1648_bill.sql
feat: add index for async flow; fix: fix bill manager master judgement; fix: fix summary synced cost
=>  feat: add index for async flow; fix: fix bill manager master judgement; fix: fix summary synced cost

front/src/views/error-pages/403.tsx
=> feat: 二级账号管理无权限说明

cmd/web-server/etc/web_server.yaml, cmd/web-server/service/service.go, pkg/cc/types.go
=> feat: web server 增加关闭账单选项

front/src/components/account-selector/index.vue, front/src/store/resource.ts, front/src/views/resource/resource-manage/children/manage/vpc-manage.vue
=> fix: 管控区列表不全&业务下账号选择器数据重复

front/index.html, front/src/views/home/index.tsx
=> feat: 账号管理功能开关配置

front/src/hooks/useTable/useTable.tsx, front/src/store/business.ts, front/src/views/business/cert-manager/index.tsx, front/src/views/business/load-balancer/clb-view/specific-clb-manager/listener-list/index.tsx, front/src/views/resource/resource-manage/hooks/use-query-list.ts
- CLB下批量删除监听器弹框功能异常
- 资源接入-证书管理，账号下的资源数据异常
=> fix: 修复线上问题

pkg/logs/glog/glog.go
logContent already been formatted
=> perf: reduce glog double printf

cmd/account-server/logics/bill/rootaccount_controller.go, cmd/account-server/logics/bill/summarydaily_controller.go, cmd/account-server/service/bill/billitem/bill_items.go, cmd/data-service/service/bill/billitem/create.go, cmd/data-service/service/bill/billitem/delete.go, cmd/data-service/service/bill/billitem/query.go, cmd/data-service/service/bill/billitem/update.go, cmd/task-server/logics/action/bill/dailysplit/dailysplit.go, cmd/task-server/logics/action/bill/dailysummary/dailysummary.go, pkg/api/data-service/bill/billitem.go, pkg/client/data-service/aws/bill.go, pkg/client/data-service/azure/bill.go, pkg/client/data-service/gcp/bill.go, pkg/client/data-service/global/bill.go, pkg/client/data-service/huawei/bill.go, pkg/client/data-service/kaopu/bill.go, pkg/client/data-service/zenlayer/bill.go, pkg/dal/dao/bill/billitem.go, pkg/dal/dao/orm/option.go, pkg/dal/dao/orm/orm.go, pkg/dal/dao/orm/orm_test.go, pkg/dal/dao/types/bill/bills.go
=> feat: 账单明细表按云厂商、年月分表

front/src/hooks/useTableListQuery.ts, front/src/plugin-handler/business-host-manage.tsx, front/src/store/business.ts, front/src/views/business/host/children/host-operations/index.module.scss, front/src/views/business/host/children/host-operations/index.tsx, front/src/views/business/host/children/host-operations/use-batch-operation.tsx, front/src/views/business/host/children/host-operations/use-single-operation.tsx, front/src/views/business/host/host-manage.vue, front/src/views/resource/resource-manage/hooks/use-filter.ts
=> refactor: 业务下主机操作插件化改造

front/src/components/global-permission-dialog/index.tsx, front/src/components/permission-dialog/index.tsx, front/src/hooks/useVerify.ts, front/src/plugin-handler/business-host-manage.tsx, front/src/store/common.ts, front/src/store/useGlobalPermissionDialog.ts, front/src/views/business/load-balancer/clb-view/all-clbs-manager/index.tsx, front/src/views/business/load-balancer/clb-view/lb-tree/index.tsx, front/src/views/business/load-balancer/group-view/all-groups-manager/index.tsx, front/src/views/home/index.tsx, front/src/views/resource/accountmanage/index.vue
=> feat: 负载均衡鉴权及体验问题优化

pkg/api/data-service/cloud/target_group.go
data service 层支持其他所有类型inst_type
--story=118862875
=> feat: 支持所有类型的负载均衡RS

pkg/thirdparty/esb/esb.go
=> feat:支持全局获取esb client

cmd/data-service/etc/data_service.yaml, cmd/data-service/service/bill/rawbill/delete.go, cmd/data-service/service/bill/rawbill/list.go, cmd/data-service/service/bill/rawbill/query.go, cmd/data-service/service/bill/rawbill/rawbill.go, cmd/data-service/service/cos/init.go, cmd/data-service/service/service.go, go.mod, go.sum, pkg/api/data-service/cos/cos.go, pkg/cc/types.go, pkg/dal/objectstore/objectstore.go, pkg/dal/objectstore/tcloud.go
=> feat(data): cos预签名url生成

cmd/cloud-server/service/application/create.go, cmd/cloud-server/service/application/handlers/account/prepare.go, cmd/cloud-server/service/application/handlers/cvm/aws/prepare.go, cmd/cloud-server/service/application/handlers/cvm/azure/prepare.go, cmd/cloud-server/service/application/handlers/cvm/gcp/prepare.go, cmd/cloud-server/service/application/handlers/cvm/huawei/prepare.go, cmd/cloud-server/service/application/handlers/cvm/tcloud/prepare.go, cmd/cloud-server/service/application/handlers/disk/aws/prepare.go, cmd/cloud-server/service/application/handlers/disk/azure/prepare.go, cmd/cloud-server/service/application/handlers/disk/gcp/prepare.go, cmd/cloud-server/service/application/handlers/disk/huawei/prepare.go, cmd/cloud-server/service/application/handlers/disk/tcloud/prepare.go, cmd/cloud-server/service/application/handlers/handler.go, cmd/cloud-server/service/application/handlers/load_balancer/tcloud/prepare.go, cmd/cloud-server/service/application/handlers/main-account/create-main-account/prepare.go, cmd/cloud-server/service/application/handlers/main-account/update-main-account/prepare.go, cmd/cloud-server/service/application/handlers/vpc/aws/prepare.go, cmd/cloud-server/service/application/handlers/vpc/azure/prepare.go, cmd/cloud-server/service/application/handlers/vpc/gcp/prepare.go, cmd/cloud-server/service/application/handlers/vpc/huawei/prepare.go, cmd/cloud-server/service/application/handlers/vpc/tcloud/prepare.go, cmd/cloud-server/service/application/init.go, cmd/cloud-server/service/application/list.go, cmd/data-service/service/application/application.go, pkg/api/data-service/application.go, pkg/dal/dao/tools/filter.go, pkg/dal/table/application/application.go, scripts/sql/9999_20240716_1757_scr_integ.sql
- feat: 增加业务下查询单据列表的接口，增加application表bk_biz_ids字段 --story=118626438
- feat: 增加主机、硬盘、VPC、负载均衡创建单据时记录业务ID --story=118626503
=> feat: 增加业务下查询单据列表的接口，增加application表bk_biz_ids字段

front/src/views/business/load-balancer/group-view/components/AddOrUpdateTGSideslider/index.tsx
=> feat: 目标组-添加RS-CVM选主IP

front/package-lock.json, front/package.json, front/src/components/copy-to-clipboard/index.vue, front/src/views/business/host/children/host-operations/index.tsx, front/src/views/business/host/children/host-operations/use-batch-operation.tsx, front/src/views/business/host/host-manage.vue, front/src/views/resource/resource-manage/common/table/HostOperations.tsx, front/src/views/resource/resource-manage/hooks/use-columns.scss, front/src/views/resource/resource-manage/hooks/use-columns.tsx
=> feat: 主机列表支持复制IP

front/src/views/bill/account/account-manage/panel/index.tsx, front/src/views/resource/resource-manage/hooks/use-columns.tsx
=> fix: 账号管理-二级账号字段顺序不正确

cmd/cloud-server/service/application/create.go, cmd/cloud-server/service/mail-verify/send.go, cmd/cloud-server/service/mail-verify/service.go, cmd/cloud-server/service/mail-verify/types.go, cmd/cloud-server/service/mail-verify/verification.go, cmd/cloud-server/service/service.go, docs/api-docs/web-server/docs/service/mail_send_code.md, docs/api-docs/web-server/docs/service/mail_verification_code.md, pkg/api/cloud-server/application/main_account.go
- feat: 增加邮箱验证码验证功能及对应的接口文档，用作多场景区分下的邮箱验证，嵌入二级账号申请提交的流程中验证
=> feat: 增加邮箱验证码验证功能及对应的接口文档，用作多场景区分下的邮箱验证，嵌入二级账号申请提交的流程中验证

cmd/account-server/logics/bill/accountlister.go, cmd/account-server/service/account-set/root-account/add.go, cmd/account-server/service/account-set/root-account/check.go, cmd/account-server/service/account-set/root-account/list.go, cmd/account-server/service/bill/billsummarymain/list.go, cmd/account-server/service/bill/billsummarymain/sum.go, cmd/account-server/service/bill/billsummaryroot/list.go, pkg/adaptor/azure/bill.go, pkg/api/account-server/bill/billsummarymain.go, pkg/api/account-server/bill/billsummaryroot.go, pkg/api/core/account-set/root_account.go, pkg/client/data-service/global/root_account.go
=> feat: 补全账单汇总账号名称

pkg/serviced/discovery.go, pkg/serviced/service.go, pkg/serviced/types.go
- fix: 增加服务启动时注册发现等etcd操作的timeout，防止没有可用etcd服务时阻塞
=> fix: 增加服务启动时注册发现等etcd操作的timeout，防止没有可用etcd服务时阻塞

cmd/cloud-server/service/load-balancer/async_target_group_add_rs.go, cmd/cloud-server/service/load-balancer/async_target_group_remove_rs.go
- fix: 修复异步向目标组增加RS、异步删除RS、修改RS权重_port时，参数转换缺失Ip赋值的问题
=> feat: 优化异步向目标组增加RS、异步删除RS、修改RS权重_port时，参数转换缺失Ip赋值的问题

cmd/account-server/service/bill/billitem/service.go, cmd/account-server/service/bill/billitem/third_party.go, cmd/auth-server/service/auth/adaptor.go, cmd/auth-server/service/auth/gen_id.go, cmd/auth-server/types/types.go, cmd/data-service/service/auth/auth.go, docs/api-docs/api-server/docs/zh/list_bill_item_for_third_party.md, pkg/api/account-server/bill/billitem.go, pkg/dal/dao/account-set/root_account.go, pkg/dal/dao/tools/filter.go, pkg/dal/dao/types/bill/bills.go, pkg/dal/dao/types/root_account.go, pkg/iam/meta/resource.go, pkg/iam/sys/initial_action_groups.go, pkg/iam/sys/initial_actions.go, pkg/iam/sys/initial_instance_selections.go, pkg/iam/sys/initial_resources.go, pkg/iam/sys/types.go
=> feat: third party bill pull api

front/src/common/constant.ts, front/src/components/business-selector/index.vue, front/src/hooks/useWhereAmI.ts, front/src/store/business.ts, front/src/utils/bill.ts, front/src/utils/common.ts, front/src/utils/lb.ts, front/src/views/bill/bill/components/search/index.tsx, front/src/views/bill/bill/components/search/sub-account-selector.tsx, front/src/views/business/load-balancer/clb-view/all-clbs-manager/index.tsx, front/src/views/business/load-balancer/clb-view/components/AddOrUpdateDomainSideslider/useAddOrUpdateDomain.tsx, front/src/views/business/load-balancer/clb-view/components/AddOrUpdateListenerSideslider/index.tsx, front/src/views/business/load-balancer/clb-view/lb-tree/index.tsx, front/src/views/business/load-balancer/group-view/components/AddOrUpdateTGSideslider/index.tsx, front/src/views/business/load-balancer/index.tsx, front/src/views/home/business-selector/index.tsx, front/src/views/home/hooks/useChangeHeaderTab.ts, front/src/views/home/index.tsx, front/src/views/resource/resource-manage/children/manage/load-balancer-manage.vue, front/src/views/resource/resource-manage/operationRecord/index.tsx, front/src/views/service/service-apply/clb/hooks/useBottomBar.tsx, front/src/views/service/service-apply/components/common/condition-options.vue
=> feat: 优化全局业务id设置

cmd/hc-service/logics/res-sync/tcloud/load_balancer_target_group.go
- fix: 修复同步资源时，RS只拉取了500条作为比对的bug
=> fix: 修复同步资源时，RS只拉取了500条作为比对的bug

front/.husky/pre-commit, front/src/common/constant.ts, front/src/views/home/business-selector/index.tsx
=> feat: 全局业务id调整向下兼容

pkg/serviced/service.go
=> feat: 修复etcd watch 错误设置timeout

front/src/common/constant.ts, front/src/components/business-selector/index.vue, front/src/hooks/useWhereAmI.ts, front/src/store/business.ts, front/src/views/home/business-selector/index.tsx, front/src/views/home/hooks/useChangeHeaderTab.ts
=> feat: 申请单据跳转链接报错-业务id

front/src/plugin-handler/resource-template-dialog.ts, front/src/typings/business.ts, front/src/utils/common.ts, front/src/views/business/business-manage.vue, front/src/views/resource/resource-manage/children/dialog/template-dialog/index.tsx, front/src/views/resource/resource-manage/children/manage/security-manage.vue, front/src/views/resource/resource-manage/resource-manage.vue
--story=118924591 【功能优化】参数模板-腾讯云
=> feat: 参数模板-腾讯云

front/src/utils/lb.ts, front/src/views/resource/resource-manage/operationRecord/RecordDetail/index.tsx, front/src/views/resource/resource-manage/operationRecord/index.tsx
=> fix: 操作记录url id冲突修复

cmd/hc-service/service/main-account/aws.go, pkg/adaptor/aws/main_account.go
=> feat: 修复aws二级账号创建异常

front/src/utils/common.ts
=> feat: 安全组参数模板-所有端口输入不区分大小写

front/src/views/business/business-manage.vue, front/src/views/service/service-apply/clb/hooks/useRenderForm.tsx, front/src/views/service/service-apply/clb/index.tsx, front/src/views/service/service-apply/components/common/condition-options.vue, front/src/views/service/service-apply/components/common/subnet-selector.tsx, front/src/views/service/service-apply/cvm/index.tsx, front/src/views/service/service-apply/disk/index.tsx, front/src/views/service/service-apply/hooks/use-condtion.ts, front/src/views/service/service-apply/subnet/index.tsx, front/src/views/service/service-apply/vpc/index.tsx
=> feat: 【前端优化】优化购买页面的业务ID数据流

cmd/hc-service/service/bill/aws.go, pkg/criteria/constant/bill.go
=> feat: Aws账单CUR报告优化

front/src/hooks/useTable/useTable.tsx, front/src/views/business/load-balancer/clb-view/specific-clb-manager/clb-detail/index.tsx, front/src/views/resource/resource-manage/hooks/use-columns.tsx, front/src/views/service/apply-list/constants.ts
=> feat: CLB跨域开关交互优化&账号管理字段调整以及单据管理搜索优化

front/src/common/util.ts, front/src/store/useBillStore.ts, front/src/views/bill/account/account-detail/first-level-account-detail/index.scss, front/src/views/bill/account/account-detail/first-level-account-detail/index.tsx, front/src/views/resource/accountmanage/account-detail.tsx, front/src/views/resource/resource-manage/account/createAccount/components/accountForm/useSecretExtension.tsx, package-lock.json
=> feat: 华为云-一级账号-编辑密钥报错

cmd/cloud-server/service/application/create.go, cmd/cloud-server/service/mail-verify/service.go, cmd/cloud-server/service/service.go, docs/support-file/helm/Chart.yaml, pkg/api/cloud-server/application/main_account.go
=> feat: 关闭邮箱验证码功能并修改chart版本号

front/src/views/bill/account/create-account/create-second-account/create-section-email/index.tsx, front/src/views/bill/account/create-account/create-second-account/index.tsx
=> feat: 创建二级账号去掉邮箱验证码

front/src/store/common.ts
=> fix: 进入资源接入后调整为不鉴权

cmd/hc-service/service/vpc/azure.go
=> feat: 资源下创建Azure的Vpc参数优化

front/src/views/home/index.scss, front/src/views/service/service-apply/components/common/BandwidthPackageSelector/index.tsx, front/src/views/service/service-apply/cvm/index.scss, front/src/views/service/service-apply/cvm/index.tsx, front/src/views/service/service-apply/hooks/use-cvm-form-data.ts, front/src/views/service/service-apply/hooks/use-cvm-options.ts
=> feat: 腾讯云购买主机支持网络计费模式

pkg/iam/sys/initial_actions.go
=> feat: 去掉业务访问的关联资源分配的选项

cmd/account-server/etc/account_server.yaml, cmd/account-server/logics/bill/mainaccount_controller.go, cmd/account-server/logics/bill/manager.go, docs/support-file/helm/values.yaml, pkg/cc/types.go
=> feat: 支持关闭账单拉取功能

front/package-lock.json, front/src/components/common-sideslider/index.tsx, front/src/hooks/useTable/index.module.scss, front/src/router/module/business.ts, front/src/style/text.scss, front/src/typings/common.ts, front/src/views/business/load-balancer/clb-view/all-clbs-manager/batch-import-comp/action-dropdown/index.vue, front/src/views/business/load-balancer/clb-view/all-clbs-manager/batch-import-comp/index.vue, front/src/views/business/load-balancer/clb-view/all-clbs-manager/batch-import-comp/operation-sideslider/base-info/index.vue, front/src/views/business/load-balancer/clb-view/all-clbs-manager/batch-import-comp/operation-sideslider/components/step.vue, front/src/views/business/load-balancer/clb-view/all-clbs-manager/batch-import-comp/operation-sideslider/index.vue, front/src/views/business/load-balancer/clb-view/all-clbs-manager/batch-import-comp/operation-sideslider/preview/index.vue, front/src/views/business/load-balancer/clb-view/all-clbs-manager/batch-import-comp/operation-sideslider/upload/index.vue, front/src/views/business/load-balancer/clb-view/all-clbs-manager/batch-import-comp/types.ts, front/src/views/business/load-balancer/clb-view/all-clbs-manager/index.tsx, front/src/views/service/service-apply/components/common/region-selector.tsx
=> feat: CLB-Excel批量导入

pkg/api/cloud-server/task/detail.go, pkg/api/cloud-server/task/management.go
feat: 调整查询异步任务状态和任务执行结果数量的输入参数 --story=119922563
=> feat: 调整查询异步任务状态和任务执行结果数量的输入参数 --story=119922563

front/package-lock.json, front/src/views/business/load-balancer/clb-view/components/AddOrUpdateListenerSideslider/useAddOrUpdateListener.ts, front/src/views/business/load-balancer/components/LbSpecTypeDialog/index.tsx, front/src/views/service/service-apply/clb/hooks/useBottomBar.tsx, front/src/views/service/service-apply/clb/hooks/useFilterResource.ts, front/src/views/service/service-apply/clb/hooks/useRenderForm.tsx
--bug=132019967 【HCM】CLB-创建HTTP监听器报错
--bug=132019897 【HCM】CLB-内网-创建时-没有选EIP，提交报错
=> fix: 修复负载均衡购买问题

cmd/cloud-server/service/load-balancer/listener.go, cmd/cloud-server/service/load-balancer/load_balancer.go, cmd/data-service/service/cloud/load-balancer/load_balancer.go, cmd/data-service/service/cloud/load-balancer/query.go, docs/api-docs/web-server/docs/biz/load-balancer/list_biz_listeners_with_targets.md, pkg/api/data-service/cloud/load_balancer.go, pkg/client/data-service/global/load_balancer.go, pkg/criteria/enumor/load_balancer.go, pkg/tools/cidr/cidr.go
=> feat: 新增查询RSIP所在监听器的接口

front/src/components/account-selector/filter.class.ts, front/src/components/account-selector/filter.plugin.ts, front/src/components/account-selector/index-new.vue, front/src/components/search/account.vue, front/src/hooks/use-search-qs.ts, front/src/hooks/use-table-settings.ts, front/src/model/task/detail.view.ts, front/src/model/typings.ts, front/src/views/task/children/data-list/column-common.ts, front/src/views/task/children/data-list/data-list.vue, front/src/views/task/children/search/search.vue, front/src/views/task/clb.vue, front/src/views/task/details/children/action-list/action-list.vue, front/src/views/task/details/children/action-list/column-common.ts, front/src/views/task/details/children/action-list/fields.ts, front/src/views/task/details/children/rerun/rerun.vue, front/src/views/task/details/clb.vue, front/src/views/task/typings.ts
- feat: clb任务管理搜索排序及展示优化
- feat: clb任务管理适配任务来源为标准运维的数据展示
- feat: clb任务重试交互问题优化
- feat: clb任务管理列表页支持表格设置
- feat: 账号选择器filter默认配置集成，支持clb展示可用账号
=> feat: clb任务管理搜索排序及展示和重试交互问题优化

cmd/task-server/logics/action/load-balancer/batch_task_common.go, cmd/task-server/logics/action/load-balancer/batch_task_tcloud_bind_targets.go, cmd/task-server/logics/action/load-balancer/batch_task_tcloud_create_l7rule.go, cmd/task-server/logics/action/load-balancer/batch_task_tcloud_create_listener.go, pkg/async/action/run/execute_kit.go, pkg/client/hc-service/tcloud/clb.go, pkg/criteria/constant/error.go, pkg/criteria/constant/rate_limit_retry.go, pkg/kit/kit.go
--story=119694441 task原子执行失败时，如果是超频错误，则重试
=> feat: CLB导入异步任务增加限频自动重试支持

front/src/views/resource/resource-manage/children/manage/security-manage.vue
=> fix: 资源接入-安全组-列表缺失备注字段的值

cmd/cloud-server/logics/load-balancer/import_executor.go, cmd/cloud-server/logics/load-balancer/import_preview_executor.go, cmd/cloud-server/logics/load-balancer/unbind_listener_rs_executor.go, cmd/hc-service/service/load-balancer/tcloud.go, cmd/hc-service/service/load-balancer/tcloud_target_group.go, cmd/task-server/logics/action/init.go, cmd/task-server/logics/action/load-balancer/batch_task_tcloud_unbind_targets.go, pkg/api/core/task/management.go, pkg/api/hc-service/load-balancer/tcloud.go, pkg/client/hc-service/tcloud/clb.go, pkg/criteria/enumor/async_flow_name.go, pkg/criteria/enumor/async_task_name.go, pkg/criteria/enumor/load_balancer.go, pkg/criteria/enumor/task.go
=> feat: 监听器批量解绑RS的异步任务接口

cmd/cloud-server/logics/load-balancer/import_executor.go, cmd/cloud-server/logics/load-balancer/import_preview_executor.go, cmd/cloud-server/logics/load-balancer/modify_listener_rs_weight_executor.go, cmd/hc-service/service/load-balancer/tcloud.go, cmd/hc-service/service/load-balancer/tcloud_target_group.go, cmd/task-server/logics/action/init.go, cmd/task-server/logics/action/load-balancer/batch_task_common.go, cmd/task-server/logics/action/load-balancer/batch_task_tcloud_modify_rs_weight.go, pkg/api/data-service/cloud/load_balancer.go, pkg/api/hc-service/load-balancer/tcloud.go, pkg/client/hc-service/tcloud/clb.go, pkg/criteria/enumor/async_flow_name.go, pkg/criteria/enumor/async_task_name.go, pkg/criteria/enumor/load_balancer.go, pkg/criteria/enumor/task.go, pkg/dal/table/task/detail.go, scripts/sql/9999_20240910_1700_task.sql
=> feat: 监听器批量调整RS权重的异步任务接口

cmd/cloud-server/logics/load-balancer/delete_listener_executor.go, cmd/cloud-server/logics/load-balancer/import_executor.go, cmd/cloud-server/logics/load-balancer/import_preview_executor.go, cmd/data-service/service/cloud/load-balancer/load_balancer.go, cmd/data-service/service/cloud/load-balancer/query.go, cmd/task-server/logics/action/init.go, cmd/task-server/logics/action/load-balancer/batch_task_common.go, cmd/task-server/logics/action/load-balancer/batch_task_tcloud_delete_listener.go, pkg/api/core/task/management.go, pkg/api/data-service/cloud/load_balancer.go, pkg/client/data-service/global/load_balancer.go, pkg/criteria/enumor/async_flow_name.go, pkg/criteria/enumor/async_task_name.go, pkg/criteria/enumor/load_balancer.go, pkg/criteria/enumor/task.go
=> feat: 批量删除监听器的异步任务接口

front/src/views/bill/bill/adjust/create/RenderTableRow/index.tsx
=> fix: 账号管理-调账功能优化

front/src/views/task/details/children/rerun/rerun.vue
=> fix: 失败任务重试编辑按钮在校验通过时设置为disabled 

cmd/task-server/logics/action/load-balancer/sync_tcloud_load_balancer.go, pkg/async/action/run/execute_kit.go, pkg/kit/kit.go
=> feat: 同步负载均衡重设rid，避免触发rid长度限制

cmd/cloud-server/service/load-balancer/listener.go, pkg/api/data-service/cloud/load_balancer.go
=> feat: 优化获取监听器及RS列表接口的参数

front/src/components/common-sideslider/index.module.scss, front/src/components/common-sideslider/index.tsx
=> fix: 抽屉提交按钮tooltips显示异常

cmd/task-server/logics/action/load-balancer/batch_task_tcloud_bind_targets.go, cmd/task-server/logics/action/load-balancer/batch_task_tcloud_create_l7rule.go, cmd/task-server/logics/action/load-balancer/batch_task_tcloud_create_listener.go, cmd/task-server/logics/action/load-balancer/batch_task_tcloud_delete_listener.go, cmd/task-server/logics/action/load-balancer/batch_task_tcloud_modify_rs_weight.go, cmd/task-server/logics/action/load-balancer/batch_task_tcloud_unbind_targets.go, cmd/task-server/logics/action/load-balancer/sync_tcloud_load_balancer.go, cmd/task-server/logics/action/load-balancer/sync_tcloud_load_balancer_listener.go
=> feat: 增加对批量任务调用云上Action的多vendor支持

cmd/hc-service/logics/cloud-adaptor/cloud_client.go, pkg/criteria/enumor/enumor.go
fix: 修复tcloud接口重试失效问题 --story=120222304
=> fix: 修复tcloud接口重试失效问题 --story=120222304

pkg/criteria/constant/time.go
=> feat: support time format of RFC3339 with millisecond in filter

front/src/utils/interval.ts, front/src/views/resource/resource-manage/accountInfo/component/resourceStatus/index.tsx
=> feat: 资源接入-账号信息-账号状态-增加自动刷新功能

front/src/components/resource-search-select/option-common.ts
=> feat: 调整主机列表搜索框字段序列

front/src/views/service/apply-detail/account-apply-detail/index.tsx
=> fix: 修复单据详情权限报错问题-创建二级账号

front/src/constants/account.ts, front/src/views/service/service-apply/account-add/index.tsx, front/tsconfig.json
=> feat: 登记账号录入校验与自动去除空格优化

docs/support-file/helm/templates/hcservice/configmap.yaml, docs/support-file/helm/templates/ingress.yaml
defaultBackend 为全局配置，会影响其他服务，需要改为默认规则
=> chore: 删除 ingress defaultBackend

cmd/cloud-server/service/account/check.go, pkg/api/cloud-server/account/create.go
=> feat: 不校验账号备注格式，关闭安全审计账号的主账号重复校验

front/src/views/service/apply-detail/account-apply-detail/index.tsx
=> fix: 修复单据详情-创建二级账号-一级账号列表数据异常问题

cmd/cloud-server/service/account/check.go, docs/support-file/helm/Chart.yaml, docs/support-file/helm/values.yaml
=> feat: CheckAccount接口校验登记账号和安全审计账号

cmd/hc-service/service/cvm/tcloud.go, pkg/adaptor/tcloud/cvm.go, pkg/adaptor/tcloud/interface.go, pkg/adaptor/types/cvm/tcloud.go, pkg/adaptor/types/poller_option.go, pkg/api/hc-service/cvm/tcloud.go
=> feat: 云主机重装hc-service、adaptor接口

cmd/cloud-server/service/application/handlers/account/check.go, pkg/api/cloud-server/account/common.go
=> feat: 去掉aws中国站校验，账号名允许大写字母

front/src/views/resource/resource-manage/children/manage/security-manage.vue, front/src/views/resource/resource-manage/resource-manage.vue
=> fix: 资源接入-切换资源后，账号无法选中

front/src/views/resource/resource-manage/children/manage/security-manage.vue
perf: 资源接入-安全组-列表-创建时间、更新时间替换云上的数据时间
feat: 安全组-列表数据-同步标签字段
=> feat: 安全组-列表数据-同步标签字段

front/src/views/service/service-apply/account-add/index.tsx
=> feat: 账号登记支持中国站

front/src/hooks/useTableSelection.ts, front/src/views/resource/resource-manage/hooks/use-selection.ts
=> fix: 表格选择数据不正确的问题修复

front/src/common/constant.ts, front/src/store/resource.ts, front/src/views/resource/resource-manage/children/components/security/security-rule-sort.vue, front/src/views/resource/resource-manage/children/components/security/security-rule.vue, front/src/views/resource/resource-manage/children/components/security/show-sort.plugin.ts
=> feat: 腾讯云-安全组规则排序

front/src/store/business.ts, front/src/store/resource.ts, front/src/views/business/load-balancer/clb-view/all-clbs-manager/account-filter.plugin.ts, front/src/views/business/load-balancer/clb-view/all-clbs-manager/index.tsx, front/src/views/business/load-balancer/clb-view/specific-clb-manager/listener-list/index.tsx
=> feat: CLB增加刷新同步功能

front/src/store/resource.ts, front/src/views/business/load-balancer/clb-view/all-clbs-manager/account-filter.plugin.ts, front/src/views/business/load-balancer/clb-view/all-clbs-manager/index.tsx, front/src/views/business/load-balancer/clb-view/specific-clb-manager/listener-list/index.tsx
Reverts TencentBlueKing/bk-hcm#1171
=> Revert "feat: CLB增加刷新同步功能"

cmd/cloud-server/service/account/rel.go, cmd/cloud-server/service/disk/rel.go, cmd/cloud-server/service/image/tcloud.go, cmd/hc-service/service/sync/handler/handler.go, go.mod, go.sum, pkg/adaptor/types/load-balancer/tcloud.go, pkg/runtime/filter/helper.go, pkg/runtime/filter/operator.go, pkg/tools/hooks/handler/operation.go
=> feat: 支持sql中文字段，修正账号关联关系列表权限

front/src/views/business/load-balancer/clb-view/all-clbs-manager/index.tsx
=> perf: 勾选了负载均衡后同步按钮置灰

front/src/views/business/load-balancer/clb-view/all-clbs-manager/batch-import-comp/operation-sideslider/index.vue, front/src/views/business/load-balancer/clb-view/lb-tree/tree/index.vue, front/src/views/task/clb.vue
=> feat: CLB导入Excel成功后跳转到任务管理页面

front/src/views/resource/resource-manage/common/info-list/info-list.tsx
=> feat: 前端优化-详情页面编辑对象异常

go.mod, go.sum
go-sql-driver/mysql v1.8.1 may casuse error: `connection.go:49: unexpected EOF`
--story=12047584
=> feat: 修复sqlx v1.4.0 报错

front/src/router/module/business.ts, front/src/views/service/service-apply/vpc/index.tsx
=> chore: 隐藏详情页面面包屑

cmd/account-server/logics/bill/monthtask/huawei.go, cmd/account-server/logics/bill/puller/huawei/huawei.go, cmd/hc-service/service/bill/huawei.go, cmd/task-server/logics/action/bill/dailypull/huawei/huawei.go, cmd/task-server/logics/action/bill/monthtask/huawei.go, cmd/task-server/logics/action/bill/monthtask/huawei_support.go, cmd/task-server/logics/action/bill/monthtask/interface.go, pkg/api/core/bill/billitem.go, pkg/api/data-service/account-set/main_account.go, pkg/api/data-service/account-set/root_account.go, pkg/api/hc-service/bill/bill.go, pkg/api/hc-service/bill/huawei.go, pkg/cc/types.go, pkg/client/hc-service/huawei/bill.go, pkg/criteria/constant/bill.go, pkg/criteria/enumor/bill.go, pkg/dal/table/cloud/account.go
=> feat: add support of Huawei cloud month task type support

cmd/hc-service/logics/res-sync/cvm-rel-manager/cvm_security_group_rel.go
=> fix: 修复getCvmSGRelMapFromDB死循环

cmd/task-server/logics/action/bill/monthtask/aws_outside_bill_month.go
=> feat: 修复月份外账单账号id错误

front/src/common/util.ts, front/src/views/business/load-balancer/clb-view/specific-clb-manager/clb-detail/index.tsx, front/src/views/resource/resource-manage/children/components/security/security-info.vue, front/src/views/resource/resource-manage/children/manage/security-manage.vue, front/src/views/resource/resource-manage/hooks/use-columns.tsx
=> feat: CLB详情/列表, 安全组-基本信息 增加tag展示

front/package-lock.json, front/package.json, front/src/components/display-value/index.vue, front/src/components/display-value/user-value.vue, front/src/components/form/user.vue, front/src/components/user-selector/index.vue, front/src/constants/storage-symbols.ts, front/src/http/index.ts, front/src/http/jsonp.ts, front/src/store/user.ts
--story=119777151
--story=120023984
=> refactor: 新的人员选择器及其展示搜索与表单组件

cmd/hc-service/service/security-group/tcloud_security_group.go, pkg/adaptor/tcloud/security_group.go, pkg/adaptor/types/security-group/tcloud.go, pkg/api/core/tag.go, pkg/api/hc-service/security_group.go
--story=120959481 腾讯云安全组创建支持打标签
=> feat: TCloud 安全组创建支持打标签

cmd/hc-service/etc/hc_service.yaml, cmd/hc-service/logics/res-sync/common/diff.go, cmd/hc-service/logics/res-sync/tcloud/load_balancer_listener.go, cmd/hc-service/service/service.go, cmd/hc-service/service/sync/handler/handler.go, cmd/hc-service/service/sync/handler/handler_test.go, cmd/hc-service/service/sync/tcloud/tcloud.go, docs/support-file/helm/values.yaml, pkg/async/consumer/executor.go, pkg/cc/service.go, pkg/cc/types.go
=> feat: 支持配置同步并发数

pkg/iam/sys/types.go
--story=121112393 将海垒在iam中的名称'海垒v2'改为海垒(HCM)
=> feat: 修改iam名称为海垒(HCM)

docs/support-file/helm/CHANGELOG.md, docs/support-file/helm/templates/_etcd.tpl, docs/support-file/helm/values.yaml
=> feat: 私有化部署的chart优化，增加etcd的tls开关等

cmd/hc-service/logics/res-sync/tcloud/load_balancer_target_group.go, pkg/adaptor/tcloud/target.go, pkg/adaptor/types/load-balancer/tcloud.go
=> feat: rs同步支持单批次同步超过100监听器

front/src/views/service/service-apply/clb/apply-clb.plugin.ts, front/src/views/service/service-apply/clb/hooks/useBottomBar.tsx
=> feat: 业务-负载均衡创建-提交后的操作plugin处理

cmd/hc-service/logics/res-sync/tcloud/cvm.go
feat: 抽出腾讯云cvm同步公共函数 --story=121049506
=> feat: 抽出腾讯云cvm同步公共函数 --story=121049506

front/src/components/sync-clb/all.vue, front/src/views/business/load-balancer/clb-view/all-clbs-manager/index.tsx, front/src/views/resource/resource-manage/children/manage/load-balancer-manage.vue
=> feat: 资源下负载均衡新增同步功能

front/src/views/business/load-balancer/clb-view/specific-clb-manager/security-group/index.scss, front/src/views/business/load-balancer/clb-view/specific-clb-manager/security-group/index.tsx
=> feat: 负载均衡安全组默认放通修正

front/src/common/constant.ts, front/src/views/bill/account/create-account/create-first-account/index.tsx, front/src/views/resource/resource-manage/account/createAccount/components/accountForm/useSecretExtension.tsx
=> feat: 一级账号录入提供新校验接口

front/src/views/service/service-apply/clb/hooks/useRenderForm.tsx
=> feat: 修复负载均衡购买-describe接口可用区传参问题

cmd/account-server/service/service.go, cmd/api-server/service/service.go, cmd/auth-server/service/handler.go, cmd/cloud-server/service/service.go, cmd/data-service/service/service.go, cmd/hc-service/service/service.go, cmd/task-server/service/service.go, cmd/web-server/service/service.go, docs/support-file/helm/CHANGELOG.md, docs/support-file/helm/templates/_etcd.tpl, docs/support-file/helm/values.yaml, pkg/serviced/serviced.go
=> feat: 调整etcd超时时间，values 增加etd超时时间配置

front/src/views/business/load-balancer/clb-view/specific-clb-manager/security-group/index.tsx
=> fix: 负载均衡绑定安全组vendor参数错误

front/src/store/resource.ts, front/src/views/resource/resource-manage/children/components/host/host-security.vue, front/src/views/service/service-apply/components/common/DraggableCard/index.tsx, front/src/views/service/service-apply/components/common/security-group-selector.tsx
=> feat: 主机-批量绑定安全组

cmd/hc-service/logics/res-sync/tcloud/load_balancer_target_group.go, cmd/hc-service/service/sync/handler/handler.go, pkg/api/core/cloud/load-balancer/tcloud.go
--story=121570774
--story=121572597
=> feat: 支持腾讯云公网clb vpc被删除的情况，优化并发同步错误提示

docs/support-file/helm/templates/accountserver/deployment.yaml, docs/support-file/helm/templates/apiserver/deployment.yaml, docs/support-file/helm/templates/authserver/deployment.yaml, docs/support-file/helm/templates/cloudserver/deployment.yaml, docs/support-file/helm/templates/dataservice/deployment.yaml, docs/support-file/helm/templates/etcd-secret.yaml, docs/support-file/helm/templates/hcservice/deployment.yaml, docs/support-file/helm/templates/taskserver/deployment.yaml, docs/support-file/helm/templates/webserver/deployment.yaml
=> feat: 优化etcd的tls开关逻辑

pkg/cc/types.go, pkg/serviced/discovery.go, pkg/serviced/service.go, pkg/serviced/types.go
=> feat: 支持etcd endpoint不可用时快速报错

front/package.json, front/src/plugin-handler/bill-manage.tsx, front/src/utils/bill.ts, front/src/views/bill/bill/index.scss, front/src/views/resource/resource-manage/hooks/use-columns.tsx
=> feat: 账号管理-多表头优化

front/src/model/cvm/properties.ts, front/src/typings/common.ts, front/src/utils/search.ts, front/src/views/resource/resource-manage/children/components/security/security-relate/bind/index.vue, front/src/views/resource/resource-manage/children/components/security/security-relate/data-list/column-common.ts, front/src/views/resource/resource-manage/children/components/security/security-relate/platform.vue, front/src/views/resource/resource-manage/children/components/security/security-relate/search/condition-common.ts, front/src/views/resource/resource-manage/children/components/security/security-relate/search/condition-factory.ts, front/src/views/resource/resource-manage/children/components/security/security-relate/search/condition-tcloud.ts, front/src/views/resource/resource-manage/children/components/security/security-relate/search/index.vue, front/src/views/resource/resource-manage/children/components/security/security-relate/unbind/batch.vue
=> feat: 安全组关联实例-增加搜索能力

front/src/views/resource/resource-manage/children/components/security/security-info.vue, front/src/views/resource/resource-manage/children/dialog/security-group/update-mgmt-type.vue, front/src/views/resource/resource-manage/children/manage/security-manage.vue
=> feat: 安全组基本信息-配置资源属主文案调整

front/src/views/resource/resource-manage/children/components/security/security-relate/data-list/collapse-data-list.vue
=> feat: 安全组-业务管理关联实例-支持绑定cvm

cmd/account-server/app/app.go, cmd/api-server/app/app.go, cmd/auth-server/app/app.go, cmd/cloud-server/app/app.go, cmd/data-service/app/app.go, cmd/hc-service/app/app.go, cmd/task-server/app/app.go, cmd/task-server/logics/action/bill/dailypull/aws/aws.go, cmd/task-server/logics/action/bill/dailypull/registry/registry.go, cmd/web-server/app/app.go, pkg/cc/service.go, pkg/cc/types.go, pkg/client/api.go, pkg/client/discovery/discovery.go, pkg/criteria/constant/service_label.go, pkg/runtime/flags/flags.go, pkg/serviced/discovery.go, pkg/serviced/discovery_test.go, pkg/serviced/service.go, pkg/serviced/serviced.go, pkg/serviced/types.go
=> feat: 服务发现支持标签、环境和不参与选主

front/src/constants/bill.ts, front/src/utils/bill.ts, front/src/views/bill/bill/components/amount/index.module.scss, front/src/views/bill/bill/components/amount/index.tsx, front/src/views/resource/resource-manage/hooks/use-columns.tsx
=> perf: 账号管理-账单字段问题修复

cmd/hc-service/service/service.go, cmd/hc-service/service/tag/tcloud.go, go.mod, go.sum, pkg/adaptor/tcloud/client.go, pkg/adaptor/tcloud/interface.go, pkg/adaptor/tcloud/tag.go, pkg/adaptor/types/tag/tcloud.go, pkg/api/hc-service/tag/tcloud.go
=> feat: 腾讯云标签hcservice接口

front/src/store/security-group/index.ts, front/src/views/resource/resource-manage/children/components/security/unclaimed-comp/index.vue, front/src/views/resource/resource-manage/children/manage/security-manage.vue
=> feat: 业务下-安全组列表-负责人接口变更联调

front/src/views/resource/accountmanage/index.vue
=> feat: 账号列表-支持按业务搜索

front/src/views/resource/resource-manage/children/components/security/unclaimed-comp/index.vue, front/src/views/resource/resource-manage/children/manage/security-manage.vue, front/src/views/resource/resource-manage/hooks/use-query-list-common.ts
=> feat: 安全组列表-count、负责人列表更改为异步行为

front/src/views/resource/resource-manage/children/components/security/security-relate/bind/index.vue, front/src/views/resource/resource-manage/children/components/security/security-relate/biz.vue, front/src/views/resource/resource-manage/children/components/security/security-relate/data-list/collapse-data-list.vue, front/src/views/resource/resource-manage/children/components/security/security-relate/data-list/index.vue, front/src/views/resource/resource-manage/children/components/security/security-relate/platform.vue, front/src/views/resource/resource-manage/children/components/security/security-relate/tab/index.vue, front/src/views/resource/resource-manage/children/manage/security-manage.vue
=> feat: 安全组关联实例-补充表格请求交互

front/src/views/resource/resource-manage/children/components/security/security-relate/bind/index.vue, front/src/views/resource/resource-manage/children/components/security/security-relate/data-list/collapse-data-list.vue, front/src/views/resource/resource-manage/children/components/security/security-relate/platform.vue, front/src/views/resource/resource-manage/children/components/security/security-relate/unbind/batch.vue, front/src/views/resource/resource-manage/children/components/security/security-relate/unbind/single.vue, front/src/views/resource/resource-manage/children/manage/security-manage.vue, front/src/views/resource/resource-manage/hooks/use-filter.ts
--story=121066141
--story=121066156
=> feat: 安全组前端优化-操作预鉴权&支持业务搜索

front/src/components/user-selector/index.vue, front/src/views/resource/resource-manage/children/components/security/security-info.vue, front/src/views/resource/resource-manage/children/components/security/security-rule.vue, front/src/views/resource/resource-manage/children/detail/security-detail.vue, front/src/views/resource/resource-manage/children/dialog/security-group/update-mgmt-attr-single.vue, front/src/views/resource/resource-manage/children/dialog/security-group/update-mgmt-attr.vue, front/src/views/resource/resource-manage/children/dialog/security-group/update-mgmt-type.vue, front/src/views/resource/resource-manage/children/dialog/security-group/usage-biz-form-item.vue, front/src/views/resource/resource-manage/children/dialog/security-group/use-account-business.ts
=> feat: 安全组-业务下可编辑控制与业务属性数据范围控制

front/src/views/resource/resource-manage/children/manage/security-manage.vue, front/src/views/resource/resource-manage/hooks/use-filter.ts
=> feat: 安全组列表-优化表格异步加载显示

front/src/views/resource/resource-manage/children/manage/security-manage.vue, front/src/views/resource/resource-manage/hooks/use-query-list-common.ts
=> feat: 安全组列表-规则数、关联实例默认展示

front/src/components/flex-tag/index.vue, front/src/views/resource/resource-manage/children/components/security/security-rule.vue, front/src/views/resource/resource-manage/children/dialog/security-group/usage-biz-form-item.vue, front/src/views/resource/resource-manage/common/tab/detail-tab.tsx
=> feat: 安全组编辑权限交互优化

front/src/store/resource.ts, front/src/views/resource/resource-manage/children/components/host/host-security.vue, front/src/views/resource/resource-manage/children/components/security/security-relate/bind/index.vue, front/src/views/resource/resource-manage/children/components/security/security-relate/data-list/collapse-data-list.vue, front/src/views/resource/resource-manage/children/components/security/security-relate/data-list/index.vue, front/src/views/resource/resource-manage/children/components/security/security-relate/platform.vue, front/src/views/resource/resource-manage/children/components/security/security-relate/unbind/batch.vue, front/src/views/resource/resource-manage/children/components/security/security-relate/unbind/single.vue
=> fix: 安全组验收-业务ID丢失&绑定刷新&增加解绑限制

front/src/views/service/service-apply/components/common/security-group-selector.tsx
=> fix: 安全组跨业务标签优化

pkg/criteria/validator/security_group.go
=> feat: 修改安全组更新校验规则

pkg/api/cloud-server/security_group.go
--story=122326722 安全组分配入参校验重复id
=> feat: 安全组分配入参校验重复id

front/src/constants/bill.ts, front/src/utils/bill.ts, front/src/views/bill/bill/index.scss, front/src/views/bill/bill/summary/change-currency.tsx, front/src/views/bill/bill/summary/primary/index.tsx, front/src/views/bill/bill/summary/product/index.tsx, front/src/views/bill/bill/summary/sub/index.tsx, front/src/views/bill/bill/use-change-currency.tsx, front/src/views/resource/resource-manage/hooks/use-columns.tsx
=> feat: 账单管理二期

front/src/http/index.ts
=> feat: 登录票据失效后登录弹窗未弹出时使用跳转至页面登录

cmd/hc-service/logics/res-sync/usage-biz-rel/sg_usage_biz_rel_manager.go, pkg/dal/dao/cloud/res_usage_biz_rel.go
=> feat: 安全组同步兼容存量数据

cmd/account-server/etc/account_server.yaml, cmd/account-server/logics/bill/monthtask/aws.go, cmd/hc-service/service/bill/aws.go, cmd/hc-service/service/bill/bill.go, cmd/task-server/logics/action/bill/monthtask/aws.go, cmd/task-server/logics/action/bill/monthtask/aws_deduct.go, cmd/task-server/logics/action/bill/monthtask/aws_savings_plans.go, cmd/task-server/logics/action/bill/monthtask/aws_support.go, docs/support-file/helm/values.yaml, pkg/adaptor/aws/bill.go, pkg/adaptor/types/bill/bill.go, pkg/api/hc-service/bill/aws.go, pkg/cc/types.go, pkg/client/hc-service/aws/bill.go, pkg/criteria/constant/bill.go, pkg/criteria/enumor/bill.go, pkg/dal/dao/bill/billitem.go
=> feat: 账号管理-账单-AWS支持指定账单剔除 --story=121621512

front/src/views/resource/resource-manage/children/components/host/host-security.vue, front/src/views/resource/resource-manage/children/dialog/clone-security/index.vue, front/src/views/resource/resource-manage/children/manage/security-manage.vue
=> fix:  更换安全组规则列表接口

docs/support-file/helm/Chart.yaml, docs/support-file/helm/values.yaml
(cherry picked from commit 6046c4b20ccc7e0fed5e501a972e399a31d3c21e)
=> docs: v1.8.0-alpha.3 - 安全组 --story=121678806

cmd/hc-service/logics/res-sync/usage-biz-rel/sg_usage_biz_rel_manager.go
=> feat: 确保使用业务为全部业务的安全组UsageBizIDs只有-1

front/src/views/business/forms/security/index.vue, front/src/views/resource/resource-manage/children/components/security/security-relate/index.vue, front/src/views/resource/resource-manage/children/components/security/security-relate/platform.vue, front/src/views/resource/resource-manage/children/components/security/security-rule.vue, front/src/views/resource/resource-manage/children/dialog/security-group/single-delete.vue, front/src/views/resource/resource-manage/children/manage/security-manage.vue, front/src/views/resource/resource-manage/hooks/use-query-list-common.ts
=> feat: 安全组详情-关联实例页面调整优化

front/src/views/bill/bill/index.scss, front/src/views/resource/resource-manage/hooks/use-columns.tsx
=> perf: 账单列表金额列右对齐

front/src/views/bill/bill/index.scss, front/src/views/resource/resource-manage/hooks/use-columns.tsx
=> perf: 调整账单非金额字段列宽

front/src/views/business/components/form-select.vue
=> fix: 新建安全组选择云账号失效

pkg/runtime/filter/operator.go, pkg/runtime/filter/operator_test.go
=> fix: 支持多重json路径

cmd/cloud-server/service/load-balancer/load_balancer.go, cmd/cloud-server/service/load-balancer/tcloud_url_rule.go, docs/api-docs/web-server/docs/biz/load-balancer/list_rule_bind_status.md, pkg/api/cloud-server/load-balancer/load_balancer.go
feat: 新增查询规则绑定目标组状态接口 --story=122411406
=> feat: 新增查询规则绑定目标组状态接口 --story=122411406

pkg/api/data-service/cloud/res_usage_biz_rel.go, pkg/dal/table/cloud/resource_usage_biz_rel.go, scripts/sql/0031_20250311_security_group_mgmt.sql
Azure 的cloud id 长度限制为255
--story=121678895
=> feat: 使用业务id支持Azure cloud id

front/src/views/resource/resource-manage/children/manage/security-manage.vue, front/src/views/resource/resource-manage/hooks/use-query-list-common.ts
=> fix: 安全组-列表页码未重置问题修复

front/src/constants/bill.ts, front/src/views/bill/bill/components/amount/index.tsx, front/src/views/bill/bill/index.scss, front/src/views/bill/bill/summary/product/index.tsx, front/src/views/bill/bill/use-change-currency.tsx, front/src/views/resource/resource-manage/hooks/use-columns.tsx
=> perf: 调整账单业务下只显示人民币字段逻辑

cmd/cloud-server/service/task/task_timing.go
feat: 优化任务管理状态判断逻辑 --story=122285714
=> feat: 优化任务管理状态判断逻辑 --story=122285714

pkg/adaptor/tcloud/cvm.go
=> feat: 主机开关机、重启优化

front/src/hooks/useMoreActionDropdown.tsx, front/src/store/common.ts, front/src/views/business/load-balancer/clb-view/all-clbs-manager/batch-import-comp/action-dropdown/index.vue, front/src/views/business/load-balancer/clb-view/all-clbs-manager/batch-import-comp/index.vue, front/src/views/business/load-balancer/clb-view/all-clbs-manager/batch-import-comp/operation-sideslider/index.vue, front/src/views/business/load-balancer/clb-view/all-clbs-manager/batch-import-comp/operation-sideslider/upload/index.vue, front/src/views/business/load-balancer/clb-view/all-clbs-manager/index.tsx, front/src/views/business/load-balancer/clb-view/components/AddOrUpdateDomainSideslider/index.tsx, front/src/views/business/load-balancer/clb-view/components/AddOrUpdateListenerSideslider/useAddOrUpdateListener.ts, front/src/views/business/load-balancer/clb-view/index.tsx, front/src/views/business/load-balancer/clb-view/lb-tree/tree/index.vue, front/src/views/business/load-balancer/clb-view/specific-clb-manager/listener-list/index.tsx, front/src/views/business/load-balancer/clb-view/specific-domain-manager/index.tsx, front/src/views/business/load-balancer/group-view/all-groups-manager/index.tsx, front/src/views/service/apply-detail/index.tsx, front/src/views/service/apply-list/constants.ts, front/src/views/service/service-apply/clb/apply-clb.plugin.ts, front/src/views/service/service-apply/clb/hooks/useBottomBar.tsx
--story=122556602
--bug=139990921
--bug=140034317
--bug=140034779
--bug=140066093
=> fix: 修复CLB问题

front/src/views/bill/bill/summary/primary/index.tsx, front/src/views/bill/bill/summary/sub/index.tsx
=> perf: 优化html tag

front/src/views/resource/resource-manage/children/components/security/security-info.vue, front/src/views/resource/resource-manage/children/components/security/security-rule-sort.vue, front/src/views/resource/resource-manage/children/components/security/security-rule.vue, front/src/views/resource/resource-manage/children/detail/security-detail.vue, front/src/views/resource/resource-manage/children/dialog/security-group/update-mgmt-type.vue
账号下-安全组-规则切换一直加载中 
业务下安全组名称/备注修改入口 显/隐逻辑没有响应 
安全组-规则排序-提交时上方按钮样式优化
账号-确认管理类型-填充负责人信息 
安全组-基本信息-使用业务出现多余换行
=> fix: 账号下-安全组-规则切换一直加载中 

front/src/views/resource/resource-manage/children/manage/plugin/show-clone.plugin.ts, front/src/views/resource/resource-manage/children/manage/security-manage.vue, front/src/views/resource/resource-manage/children/plugin/security-group/show-clone.plugin.ts
=> feat: 安全组-非腾讯云禁用克隆功能

front/src/views/resource/resource-manage/operationRecord/RecordDetail/index.tsx
=> feat: 异步任务-操作记录-去掉重试与终止逻辑优化

front/src/components/sync-clb/all.vue, front/src/views/business/load-balancer/clb-view/all-clbs-manager/index.tsx
=> feat: 同步负载均衡-在业务中使用业务账号列表接口

cmd/account-server/etc/account_server.yaml, cmd/account-server/logics/bill/monthtask/aws.go, cmd/task-server/logics/action/bill/monthtask/aws.go, cmd/task-server/logics/action/bill/monthtask/aws_deduct.go, docs/support-file/helm/values.yaml
=> feat: 优化aws月度任务逻辑

front/src/http/index.ts, front/src/store/resource.ts, front/src/views/resource/resource-manage/children/dialog/security-group/single-delete-button.plugin.vue, front/src/views/resource/resource-manage/children/dialog/security-group/single-delete-button.vue, front/src/views/resource/resource-manage/children/dialog/security-group/single-delete.vue, front/src/views/resource/resource-manage/children/manage/security-manage.vue
=> perf: 安全组删除plugin化

cmd/data-service/service/cloud/cvm/update.go, pkg/api/data-service/cloud/cvm.go
=> feat: data-service cvm 支持更新本地vpc_ids、subnet_ids、machine_type、os_name

cmd/cloud-server/logics/security-group/assign.go, cmd/cloud-server/service/security-group/assign.go, cmd/cloud-server/service/security-group/init.go, cmd/cloud-server/service/security-group/query.go, cmd/cloud-server/service/security-group/related_resource.go
=> fix: 安全组批量分配鉴权错误、移除废弃接口代码

front/src/components/security-group-selector-dialog/index.vue, front/src/store/security-group/index.ts, front/src/typings/common.ts, front/src/views/resource/resource-manage/children/components/host/host-security.vue
=> feat: 增加新的安全组选择组件

front/src/views/service/service-apply/components/common/security-group-selector.tsx
=> fix: 申请主机-不能选择安全组

front/src/views/resource/resource-manage/children/components/security/usage-biz-value.vue, front/src/views/resource/resource-manage/children/dialog/security-group/single-delete-button.plugin.vue, front/src/views/resource/resource-manage/children/dialog/security-group/single-delete-button.vue, front/src/views/resource/resource-manage/children/dialog/security-group/single-delete.vue
=> perf: 安全组删除组件useAttrs修改为props

cmd/cloud-server/service/security-group/list_rule.go
TCloud: cloud_policy_index 从小到大
Huawei: priority 从小到大
Azure: priority 从小到大
--story=123795555
=> feat: 安全组规则强制排序

front/src/components/auth/auth.vue
=> fix: 权限申请未正确展示关联资源

cmd/task-server/logics/action/load-balancer/batch_task_common.go, pkg/api/data-service/task/management.go, pkg/async/consumer/executor.go
=> feat: 任务管理-任务失败逻辑及终止任务参数优化

cmd/task-server/logics/action/bill/monthtask/aws_deduct.go, pkg/api/hc-service/bill/aws.go
=> feat: aws账单税费抵扣优化

cmd/web-server/service/service.go, docs/support-file/helm/templates/authserver/deployment.yaml, docs/support-file/helm/values.yaml
=> feat: allowHeader新增多租户ID字段、新增authDisabled配置

front/src/views/resource/resource-manage/children/components/security/security-relate/bind/index.vue
=> feat: 安全组-关联实例新增弹框过大 --story=124013063

docs/support-file/helm/templates/accountserver/configmap.yaml, docs/support-file/helm/templates/cloudserver/configmap.yaml, scripts/sql/9999_20250409_1000_add_tenant_id.sql
=> feat: 提交资源相关的DAO层改造

cmd/data-service/service/tenant/service.go, cmd/data-service/service/tenant/tenant.go, pkg/api/data-service/tenant/tenant.go, pkg/client/data-service/global/tenant.go, pkg/dal/dao/tenant/tenant.go, scripts/sql/0033_20250612_tenant.sql
移除租户表的删除相关接口，删除多余空白行，加强数组长度校验，修改租户表的collate函数
=> fix: 移除租户表的删除相关接口，删除多余空白行，加强数组长度校验，修改租户表的collate函数

docs/support-file/helm/CHANGELOG.md, docs/support-file/helm/templates/accountserver/deployment.yaml, docs/support-file/helm/templates/apiserver/deployment.yaml, docs/support-file/helm/templates/authserver/deployment.yaml, docs/support-file/helm/templates/cloudserver/deployment.yaml, docs/support-file/helm/templates/dataservice/deployment.yaml, docs/support-file/helm/templates/hcservice/deployment.yaml, docs/support-file/helm/templates/taskserver/deployment.yaml, docs/support-file/helm/templates/webserver/deployment.yaml, docs/support-file/helm/values.yaml
**由于deployment的spec.selector这个属性一旦设定就不能修修改， 会导致helm 升级失败，需要重新部署helm release**
--story=124788437
=> feat: 修正match labels

cmd/cloud-server/logics/load-balancer/layer4_listener_bind_rs_preview_executor.go, cmd/cloud-server/logics/load-balancer/layer7_listener_bind_rs_preview_executor.go, cmd/data-service/service/global-config/global_config.go, pkg/api/core/global-config/global_config.go, pkg/api/data-service/global_config/global_config.go
=> feat: 全局配置表支持泛型、同步CLB校验错误报错

front/src/components/business-selector/index.vue, front/src/views/resource/resource-manage/children/dialog/batch-distribution/index.tsx
=> feat: 资源分配-可选的业务范围在账号的使用业务内

front/src/common/constant.ts, front/src/components/RenderDetailEdit/index.tsx, front/src/components/business-selector/business.vue, front/src/components/form/business.vue, front/src/constants/account.ts, front/src/typings/account.ts, front/src/views/resource/accountmanage/account-detail.tsx, front/src/views/resource/accountmanage/index.vue, front/src/views/resource/resource-manage/account/createAccount/components/accountForm/index.tsx, front/src/views/service/apply-detail/account-apply-detail/index.tsx
接入账号-支持管理业务、使用业务
资源账号详情-支持管理业务切换
资源账号-同步状态-增加主机资源同步状态
账号详情业务字段逻辑调整
=> feat: 接入账号-支持管理业务、使用业务

pkg/rest/handler.go, pkg/rest/request.go, pkg/tools/slice/slice.go, pkg/tools/slice/slice_test.go
=> feat: 增加工具函数
